### ISSUE TITLE
Mail Bestätigung

### ISSUE THREAD

**Issue by thomassss** [h-da/geli#1]
# User Story

### als: 
Anwender

### möchte ich:
eine Bestätigungsmail nach dem Registrieren bekommen

### damit ich:
meinen Account verifizieren kann

### Akzeptanzkriterien:
Mail mit Bestätigungslink wird versendet
Bestätigung wird nach anklicken des Links in Datenbank gespeichert

**Comment by aeimer** [comment]
@khase is this issue done?

**Comment by aeimer** [comment]
i will close this
