### ISSUE TITLE
Javascript "Code Katas" units

### ISSUE THREAD

**Issue by d89** [h-da/geli#100]
# User Story

### As a: 

Teacher

### I want:

... to provide my students with multiple code katas for a section

### so that:

... the students can assess themselves and I as teacher can see the progress of them

## Acceptance criteria:

- [x] as discussed together: 3 sections might be a good way to organize the katas: 
    - [x] the task itself (can be put as a code comment "//") and the already defined variables
    - [x] the code area where the student has to put the code to reach the defined goal which is ...
    - [x] ... displayed in section 3
- [x] either pass the result to a promise or a pre-defined function
- [x] errors should be shown in a sidebar similar to es6katas.org (`window.onerror`)
- [ ] If I use a completely outdated browser (mainly IE < 11) I want to be presented with a warning. Consider using feature detection instead of browser sniffing
- [x] Syntax highlighting is required
- [x] The progress of the students should be shown to the teacher as described in #99

### Example-Task 1

```javascript
// Task: Generate all numbers between 1 and 100, that are divisible by 3 AND 5 

let min = 1;
let max = 100;
let genNumbers = [];

//####################

for (let i = min; i <= max; i++) {
    if (i % 3 === 0 && i % 5 === 0) {
        genNumbers.push(i);
    }
}

//####################

validate();

function validate() {
    return genNumbers.join(",") === "15,30,45,60,75,90";
}
```

### Example-Task 2

```javascript
// Task: Manipulate the targetSet, so it only contains the values "Hello" and "h_da"

let targetSet = new Set(["Hello", "there"]);

//####################

targetSet.add("h_da");
targetSet.delete("there");

//####################

validate();

function validate() {
    return targetSet.has("Hello") && targetSet.has("h_da") && targetSet.size === 2;
}
```

**Comment by d89** [comment]
This issue is a "small version" of #44 which handles the full integration using docker containers to be able to support every kind of programming language.

**Comment by PatrickSkowronek** [comment]
@d89 there is only one bullet point left. After that can this be closed?
