### ISSUE TITLE
Update to Node 8

### ISSUE THREAD

**Issue by aeimer** [h-da/geli#121]
# User Story

### As a: 
developer

### I want:
to update to Node v8

### so that:
we can use npm 5.0 (see #115) and are using a LTS supported till december 2019

## Acceptance criteria:
- [x] project uses node 8
- [x] travis uses node 8
- [ ] vagrant uses node 8
- docker uses node 8
  - [x] dev
  - [x] docker-hub
- [x] Update all Dependencies, but at least:
  - tslint (api and fe to the same version)
  - npm

## Additional info:
https://github.com/nodejs/LTS#lts-schedule1

**Comment by aeimer** [comment]
This issue is scheduled for the beginning of the wintersemester 17/18

**Comment by aeimer** [comment]
> ...psst! While Bower is maintained, we recommend yarn and webpack for new front-end projects! 

As this comments is placed on the <https://bower.io>'s website, we should consider using eg yarn for the FE-Packaing stuff. This task could be done with the move to Node8 and NPM5.

**Comment by grosspersky** [comment]
tslint should also be updated and unified in Backend and Frontend. Currently we are using:
- Backend: 4.3.1
- Frontend: 4.5.1

The newest release of tslint is 5.4.2.

**Comment by aeimer** [comment]
From Ocotber 2017 NodeJS 8 is the official LTS Version, we should consider using the new Version from now on.

https://github.com/nodejs/LTS#release-schedule1

**Comment by aeimer** [comment]
Our plan is to setup a proper testing, which runs all test with codecoverage report and after that update the project. So this ticket may be interessting at the mid of this semester...

**Comment by d89** [comment]
Not sure how to review that in the frontend - I'm sure it's node 8 👍
