### ISSUE TITLE
Use different databases for prod, dev and testing

### ISSUE THREAD

**Issue by felixbrucker** [h-da/geli#135]
# User Story

### As a: 

Developer

### I want:

to use different databases for production, development and testing purposes

### so that:

no data is accidentally dropped and i can test with confidence

## Acceptance criteria:

- [x] api tests use their own test database
- [x] regular development api servers use their own dev database
- [x] production deployments use their own prod database

## Additional info:

eg. possible via ENV vars

**Comment by aeimer** [comment]
Currently we have different docker instances of mongo db for staging and prod. The naming 'test' of the db should be changed to something like 'geli'. If tests run we should put them in a database named 'test'. 
Furthermore we should implement a automated way, even if it gets triggered manually, to dump the prod db and load it into the staging db. Also there should be big set of fixtures that are automatically loaded into the staging system each time the CI triggers a new build

**Comment by aeimer** [comment]
@felixbrucker can we close this ticket?

**Comment by felixbrucker** [comment]
@aeimer i do not think this got implemented already? Ideally if i run the tests all my data in my db is still intact after the tests ran. As far as i know this currently is not the case.

**Comment by aeimer** [comment]
Ahh, ok. I have understood it in the server context. Yes you are right, at this point we can improve the flow.

**Comment by d89** [comment]
Not sure on how to review this - I'm sure it's fine 👍
