### ISSUE TITLE
Setup Travis

### ISSUE THREAD

**Issue by khase** [h-da/geli#14]
Setup the Travis CI.

### Backend
- [X] Linter _(This is executed with the test-command)_
- [X] Tests

### Frontend
- [X] Linter
- [ ] Tests
- [X] End2End Tests
- [ ] use [Chrome 59+ headless](https://developers.google.com/web/updates/2017/04/headless-chrome) so we do not need xvfb
  - We have to check before that the testframeworks are compatible with Chrome 59+ (headless)

**Comment by aeimer** [comment]
Basic Setup merged with #25

**Comment by aeimer** [comment]
Frontend Tests need to be fixed... E2E Tests are Running.

**Comment by aeimer** [comment]
Will close this issue
- chrome headless may be replaced by <https://saucelabs.com/open-source>
- the karma-angular-unit-tests have to be set up
- the codecoverage have to be setup

**Comment by aeimer** [comment]
See #127 and #94

**Comment by aeimer** [comment]
@thomassss can you help us to be able to run all tests and setup a codecov integration? I have tried it last semester, but I couldn't get it running...
