### ISSUE TITLE
Change mail sender to an official @h-da.de adress

### ISSUE THREAD

**Issue by d89** [h-da/geli#148]
This is what works for the gitlab server:

```
'use strict';
const nodemailer = require('nodemailer');

// create reusable transporter object using the default SMTP transport
let transporter = nodemailer.createTransport({
    host: 'smtp.h-da.de',
    debug: true,
    tls: {rejectUnauthorized: false},
    port: 25
});

let mailOptions = {
    from: '"Gitlab" <gl@h-da.de>',
    to: 'foobar@gmail.com',
    subject: 'Hello!',
    text: 'Hello world?',
};

// send mail with defined transport object
transporter.sendMail(mailOptions, (error, info) => {
    if (error) {
        return console.log(error);
    }
    console.log('Message %s sent: %s', info.messageId, info.response);
});
```
And this is the corresponding gitlab config:

```
gitlab_rails['smtp_enable'] = true
gitlab_rails['smtp_address'] = 'smtp.h-da.de'
gitlab_rails['smtp_port'] = 25
gitlab_rails['smtp_domain'] = 'smtp.h-da.de'
gitlab_rails['smtp_authentication'] = false
gitlab_rails['smtp_enable_starttls_auto'] = false
gitlab_rails['smtp_tls'] = false
gitlab_rails['smtp_openssl_verify_mode'] = 'none'
gitlab_rails['gitlab_email_from'] = 'gl.fbi@h-da.de'
```
Pay attention to the SSL verification being disabled. No account is required.

**Comment by aeimer** [comment]
How should we name the adresses?
- `geli.fbi@h-da.de`
- `staging.geli.fbi@h-da.de`
- `support.geli.fbi@h-da.de` => We could use this for eg uptimerobot or the ssl-contact info. The internal IT then have to forward incomming mails to several adresses like yours @d89

**Comment by d89** [comment]
Agreed to use the first 2 addresses. For the third one, we would need to open another ticket with it-services so we could actually receive mails aswell. I would keep it low for now as I don't want to flood them with too many tickets. Could be considered later 👍.
