### ISSUE TITLE
Last minute fixes

### ISSUE THREAD

**Issue by alexweinfurter** [h-da/geli#153]
# Acceptance criteria:
- [ ] Default Icons for file upload
- [x] As a teacher I can drag & drop the arrangement of the units change, but it does not seem to be saved. (Both lecture / units)
- [x] Duplicate lecture does not work as desired. Contains the same reference to the task unit as the original
- [x] Delete lecture does not delete any associated units and thus also no task units are deleted
- [x] When you are logged as student you can go into course when you are not enrolled.

**Comment by bernd-hda** [comment]
Also im manage content als teacher, kann ich per drag&drop die Anordnung der Units ändern, aber es scheint nicht gespeichert zu werden. (sowohl lecture/units)

Weiterer offener Punkt: duplicate lecture geht nicht wie gewünscht. Enthält die gleiche Referenz zur task unit wie das Original

Weitere offener Punkt: delete lecture löscht keine zugehörigen units und somit werden auch keine task units gelöscht

**Comment by khase** [comment]
can thisone be closed?

**Comment by aeimer** [comment]
@alexweinfurter ?

**Comment by alexweinfurter** [comment]
I've tested all acceptance criteria. Everything works just fine. I'll close the issue.
