### ISSUE TITLE
Switch to "official" SSL certificates

### ISSUE THREAD

**Issue by d89** [h-da/geli#160]
We finally received the official SSL certificates. On the live server, you'll find the servers private key in `/root/privkey.pem` and the SSL certificates for both `staging.geli.fbi.h-da.de` and `geli.fbi.h-da.de` in the folder `/root/ssl`

However, a certificate chain is needed that connects the root cert "T-TeleSec GlobalRoot Class 2" with these ssl certificates. You can find the certificate chain [on this page](https://pki.pca.dfn.de/dfn-ca-global-g2/cgi-bin/pub/pki?cmd=getStaticPage;name=index;id=2;RA_ID=2530) - more specifically [here](https://pki.pca.dfn.de/dfn-ca-global-g2/pub/cacert/chain.txt).

Please combine each ssl certificate with the chain following the [nginx specification](http://nginx.org/en/docs/http/configuring_https_servers.html#chains):

> In this case the authority provides a bundle of chained certificates which should be concatenated to the signed server certificate. The server certificate must appear before the chained certificates in the combined file

Finally, validate the SSL strength using a tool like https://www.ssllabs.com/ssltest/

**Comment by aeimer** [comment]
I installed the Certs.
I think were good! Some super low Programms can't handle our ssl, but we can ignore that...

https://www.ssllabs.com/ssltest/analyze.html?d=staging.geli.fbi.h-da.de
https://www.ssllabs.com/ssltest/analyze.html?d=geli.fbi.h-da.de

**Comment by d89** [comment]
Wow, that was quick. Awesome 👍
