### ISSUE TITLE
Shall we add a Changelog?

### ISSUE THREAD

**Issue by aeimer** [h-da/geli#161]
# User Story

### As a: 
organisation using geli

### I want:
to have a changelog available

### so that:
I know which new features and bugfixes are implemented

## Acceptance criteria:
- [ ] A changelog.md created
- [ ] the changelog.md is uptodate back to version 0.1.0

**Comment by PatrickSkowronek** [comment]
We should add a file which shows any change(changelog.md). Any Developer should add his changes in there before it is merged into the develop. @aeimer what do you think about that?

**Comment by aeimer** [comment]
@PatrickSkowronek seems to be a good idea. You may add a check to Travis... You may have a look at keepachangelog.com
