### ISSUE TITLE
Editing tasks not implemented

### ISSUE THREAD

**Issue by lukaskorte** [h-da/geli#162]
Editing tasks in the "Manage content" section of a course is not yet implemented.

## Acceptance criteria:

- [x] Save button saves changes

- [x] Save button also saves updates to tasks/questions (making the update button obsolete)

- [x] Update button is removed

- [x] Cancel button discards unsaved changes

- [x] Delete button removes question i.e. task

**Comment by micpah** [comment]
Added acceptance criterias

**Comment by d89** [comment]
Looks good 👍
