### ISSUE TITLE
Tagged Builds do not push a image to docker

### ISSUE THREAD

**Issue by aeimer** [h-da/geli#168]
Happened here: https://travis-ci.org/h-da/geli/builds/248483192#L908
The docker build should build the app and push a new Tag to the dockerhub, instead the build and push of the image was skipped:
```bash
$ .travis/docker.sh
+++ Run docker build and publish. +++
+ WARNING: branch v0.2.0 is not whitelisted -> skipping docker build and publish
```

**Comment by khase** [comment]
I pushed this tag manually.
https://hub.docker.com/r/hdafbi/geli-api/tags/
https://hub.docker.com/r/hdafbi/geli-web-frontend/tags/

I don't know how bash and travis behaves. 
I thought `if [ -z ${TRAVIS_TAG+x}  ]; then` should do the trick...
Maybe travis does not set the variable right or the bash line does not nork as we suspected. 

We should test this on my personal repo khase/geli
