### ISSUE TITLE
Randomize Tasks after validating

### ISSUE THREAD

**Issue by aeimer** [h-da/geli#170]
# User Story

### As a: 
Student

### I want:
to have the tasks answers randomized

### so that:
I have to know the correct answer and not the position of the right and wrong answers.
This will help me to learn the stuff better.

## Acceptance criteria:
- [x] After a click on `Validate` the correct answers are shown (like it is currently)
- [x] After a click on `Retry` the answers are shown in a randomized order
- [X] on page load randomize answers

**Comment by d89** [comment]
Sometimes, there is weird behavior when taking questions again. The correct answers are not marked accordingly:

![image](https://user-images.githubusercontent.com/423154/33343182-bc7af568-d484-11e7-8938-b3aef1508884.png)

**Comment by aeimer** [comment]
@d89 from your Screenshot I can't see any bugs. The both ticket Answers are red because they are not ticket and they should be, as visible on the right half?!

**Comment by d89** [comment]
If I select something, and then re-validate, it then looks like this:

![image](https://user-images.githubusercontent.com/423154/33343941-62d60a68-d487-11e7-9baa-85dc470139b7.png)

Sorry for the initial wrong screenshot.

**Comment by aeimer** [comment]
related to #347 

I think we can close this issue. 
I will investiagate the problem
