### ISSUE TITLE
Create TMP Folder in docker container

### ISSUE THREAD

**Issue by aeimer** [h-da/geli#172]
Setup a tmp folder for uploads automatically (API).

**Comment by d89** [comment]
Most likely related: When editing a course, I can not upload a CSV-file - error message: `Error: ENOENT: no such file or directory, open &#39;tmp/a1e46511fbe770f156e0661340f8f7fb.docx&#39`

**Comment by aeimer** [comment]
Added `RUN mkdir -p /usr/src/app/tmp`
See #196
