### ISSUE TITLE
Editing profile does not work as expected

### ISSUE THREAD

**Issue by d89** [h-da/geli#178]
When editing the profile as teacher without filling the fields "current password", "password" or "confirm password", I receive the following stack trace and a not-very userfriedly toast notifaction telling me about an http error 500.

`{"name":"ValidationError","message":"User validation failed: password: Path `password` is required.","stack":"MongooseError: User validation failed: \n    at ValidationError (/usr/src/app/node_modules/mongoose/lib/error/validation.js:27:11)\n    at model.Document.invalidate (/usr/src/app/node_modules/mongoose/lib/document.js:1592:32)\n    at /usr/src/app/node_modules/mongoose/lib/document.js:1464:17\n    at validate (/usr/src/app/node_modules/mongoose/lib/schematype.js:745:7)\n    at /usr/src/app/node_modules/mongoose/lib/schematype.js:790:11\n    at Array.forEach (native)\n    at SchemaString.SchemaType.doValidate (/usr/src/app/node_modules/mongoose/lib/schematype.js:750:19)\n    at /usr/src/app/node_modules/mongoose/lib/document.js:1462:9\n    at _combinedTickCallback (internal/process/next_tick.js:73:7)\n    at process._tickCallback (internal/process/next_tick.js:104:9)","errors":{"password":{"message":"Path `password` is required.","name":"ValidatorError","properties":{"type":"required","message":"Path `{PATH}` is required.","path":"password","value":""},"kind":"required","path":"password","value":""}},"_message":"User validation failed"}`

On top of that, "Current Password" is not validated when editing the password - I can put whatever I want, it is not validated.

**Comment by grosspersky** [comment]
I'm not able to reproduce a toast message showing this stack trace. My toast only show's this message:
```
Cancel
Response with status: 500 Internal Server Error for URL: http://localhost:4200/api/users/59a475eb831ca1248cabc796
```
The backend server also doesn't show this message and only this error message:
```
MongooseError: User validation failed:
    at ValidationError (D:\Git\geli\api\node_modules\mongoose\lib\error\validation.js:27:11)
    at model.Document.invalidate (D:\Git\geli\api\node_modules\mongoose\lib\document.js:1592:32)
    at D:\Git\geli\api\node_modules\mongoose\lib\document.js:1464:17
    at validate (D:\Git\geli\api\node_modules\mongoose\lib\schematype.js:745:7)
    at D:\Git\geli\api\node_modules\mongoose\lib\schematype.js:790:11
    at Array.forEach (native)
    at SchemaString.SchemaType.doValidate (D:\Git\geli\api\node_modules\mongoose\lib\schematype.js:750:19)
    at D:\Git\geli\api\node_modules\mongoose\lib\document.js:1462:9
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```
However it is possible to reproduce an error if leaving the password fields empty and I will investigate.

**Comment by grosspersky** [comment]
Has been solved successfully.
