### ISSUE TITLE
Logout-Behavior when having accessed an action I am not permitted to

### ISSUE THREAD

**Issue by d89** [h-da/geli#179]
I do not want to be logged out automatically, when I perform an action I am not permitted to. For example, when I click the "edit" button on a course I am not permitted to edit, I end up being logged out.

**Comment by khase** [comment]
related #173 
maybe duplicated?

**Comment by d89** [comment]
Definitely related, not sure if a duplicate :).

**Comment by lukaskorte** [comment]
Duplicats #173
