### ISSUE TITLE
Video upload does not understand the "avi"-extension

### ISSUE THREAD

**Issue by d89** [h-da/geli#184]
The file selector does not match "avi", so I have to select "All files" before I can upload anything.

**Comment by felixbrucker** [comment]
currently there is no server side conversion of video files, so they will need to be in the correct format playable by browsers (see https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats)

should server side conversion be implement or should one be able to just upload non-standard video files as video unit even though they likely wont play in most/all browsers? (one can still upload non-standard video files as regular file unit)

**Comment by d89** [comment]
I think we should avoid server side conversion. Isn't avi just a container, that might actually be playable by browsers, if it is rendered with a fitting codec?

**Comment by felixbrucker** [comment]
The current state is a tricky question, you are right that avi is "just" a container, but many browser do only support few containers (as well as codecs)
here is a support matrix for some well known browsers: https://en.wikipedia.org/wiki/HTML5_video

i know that chrome tends to support some more (mkv container at least), but others might not, one will need to test this with a variety of containers, formats and browsers for all non listed formats

**Comment by utetrapp** [comment]
solution: add avi to whitelist

**Comment by d89** [comment]
The video upload seems to be fully broken at the moment. Not sure if this issue has to do with the problem. When I click "Upload videos", the items above the floating action button stay there. When I then try to upload something, the UI behaves accordingly but the video upload does never finish. It always says "uploading".

![image](https://user-images.githubusercontent.com/423154/33342010-df81b4ec-d480-11e7-87f8-40c1a520834f.png)

**Comment by felixbrucker** [comment]
This pr with its single line changed certainly isn't to blame :D

**Comment by felixbrucker** [comment]
closing here
