### ISSUE TITLE
Course "active: true" and "active: false" feature does not seem to work

### ISSUE THREAD

**Issue by d89** [h-da/geli#185]
The "active: false" and "active: true" switch does not behave as expected. When I set the switch to "active: false" I would expect the course to be hidden on the frontpage for everyone, that is not admin or teacher of this very course. Currently, a newly signed up student that is not enrolled in this course can see it, even if it is "active: false".

**Comment by khase** [comment]
@OliverNeff you added this with 04475d9d468eb2387199ee527596a5130b99be95

**Comment by khase** [comment]
related #18

**Comment by OliverNeff** [comment]
This button was there before us. We don't react on our active flag until now. I make it just possible to set this flag.

**Comment by d89** [comment]
Please either hide the courses that are not active or remove the flip switch.

**Comment by d89** [comment]
Very nice 👍 !
