### ISSUE TITLE
Dragging and Dropping Lectures in the "Edit Course" section can lead to the deletion of all the lectures

### ISSUE THREAD

**Issue by d89** [h-da/geli#188]
When messing around with the drag and drop feature while rearranging lectures and material within lectures, from time to time, stuff gets deleted.

**Comment by OliverNeff** [comment]
This is also a problem by managing member is course. 
I think it is a problem how we use dracula in our context.

**Comment by aeimer** [comment]
@OliverNeff haven't you fixed this Issue?

**Comment by aeimer** [comment]
is #131 related?

**Comment by d89** [comment]
Did not occur any more :). Good job.
