### ISSUE TITLE
Send e-mails to course members

### ISSUE THREAD

**Issue by OliverNeff** [h-da/geli#19]
# User Story

### As:
teacher 

### I want to:
send an email to an specific member, all member or an amount of members for his information. 

### As a result:
I can inform students.

**Comment by d89** [comment]
Added criteria in the session on 2017-11-30:

- [ ] add a button to send to all course members
- [ ] Set all the teachers as CC
- [ ] Set the sending person as "ReplyTo"

**Comment by felixbrucker** [comment]
@d89 i already created a new issue for these enhancements ;) see https://github.com/h-da/geli/issues/408

closing here

**Comment by d89** [comment]
Whoops - #408
