### ISSUE TITLE
Automatically enroll whitelisted users for the course they are whitelisted for

### ISSUE THREAD

**Issue by d89** [h-da/geli#191]
no text :).

**Comment by d89** [comment]
okay, I see you found it 👍 Was just searching for this issue to notify you, @OliverNeff

**Comment by OliverNeff** [comment]
Also delete user if whitelistUser is delete from course.

**Comment by d89** [comment]
Does not seem to work, check the screenshot:

![enrollment](https://user-images.githubusercontent.com/423154/35198552-c9df0d0c-fef0-11e7-895b-f8b71322d954.png)

**Comment by OliverNeff** [comment]
Ohh I thought this feature was for users which are signing in to geli. 
There is a pull request #493 which is not merged until now, which do that.
