### ISSUE TITLE
"Report" functionality - what does it do?

### ISSUE THREAD

**Issue by d89** [h-da/geli#192]
The "report"-function leads me to an empty page. When I click the "chart line"-icon on a course tile, I ended up on https://staging.geli.fbi.h-da.de/course/597df6d5b7a9c0000616637f/report - which gave me an empty page.

**Comment by grosspersky** [comment]
The report page currently only displays something if the course has students assigned.
Maybe we should display a corresponding message on the page, that informs about why nothing else is shown.
