### ISSUE TITLE
Set up the live server before the new semester starts

### ISSUE THREAD

**Issue by d89** [h-da/geli#193]
Set up the live server with Thomas, Christopher and me as administrators and no other courses in the system so we have a blank canvas.

**Comment by aeimer** [comment]
I've installed all OS updates on the server and improved the settings of the nginx reverse.

**Comment by d89** [comment]
@utetrapp needs the live system in order to present the project to potential new students that join us starting this semester. As soon as we have the live system ready, I want to set up Fortgeschrittene Webentwicklung with real content and a user for Ute, so that we can present the real system. Please message me, as soon as I can start.

**Comment by khase** [comment]
The live system is resetted so that you can setup Fortgeschrittene Webentwicklung.

**Comment by aeimer** [comment]
Can we close this ticket then?
