### ISSUE TITLE
Integrate a crashlogger

### ISSUE THREAD

**Issue by d89** [h-da/geli#200]
# User Story

### As an: 

Administrator

### I want:

... to be sure, that every uncaught exception and every error of the system is caught

### so that:

... I know bugs before users report them

## Acceptance criteria:

- [ ] Suggested Crash logging platforms are Sentry (we use Sentry @ Incloud -> selfhosted), Rollbar and Raygun.
- [ ] Cloud version or self hosted (to discuss!)
- [ ] Frontend and backend are connected with the crash logger
- [ ] Seperate environments for staging and production, NOT enabled for development.

**Comment by khase** [comment]
I have privately used the open source [ELK-Stack/Elastic-Stack](https://www.elastic.co/de/products) and was slightly overwhelmed by its possibilities.
Would definitly be worth a look.

**Comment by d89** [comment]
Yeah, we use the ELK-stack aswell and should  - in my opinion - stay away from it for GELI as it would be a project on its own to properly configure and integrate the ELK-stack.

**Comment by d89** [comment]
The Gitter integration is cool. Where can I find the password for the installation?

Let's review that in person on thursday, I will put it to "reviewed" for now.
