### ISSUE TITLE
Restyle "tables"

### ISSUE THREAD

**Issue by aeimer** [h-da/geli#214]
# User Story

### As a: 
User

### I want:
to have nice looking table

### so that:
the shifting per line that occurs currently shall be removed.

## Acceptance criteria:
- [ ] The columns are perfeclty alligned under each other

## Additional info:

![img_20171012_111752](https://user-images.githubusercontent.com/25035182/31510979-8b97df56-af86-11e7-9140-855821d29b49.jpg)

**Comment by khase** [comment]
Your picture is hardly readable.

**Comment by aeimer** [comment]
It have to mean `"task"` not `" task"`.

**Comment by khase** [comment]
This isn't a typo:
![image](https://user-images.githubusercontent.com/26968077/31577574-5f7b9cb4-b111-11e7-85e8-cbef2f399ae8.png)

This is probbably caused due to the fact we are using the flex attribute to make this spacing but this does not work well with variable content length.

**Comment by aeimer** [comment]
Ahh all right, but thats super ugly! We need to change this...

Found an ever worse exmaple:
![grafik](https://user-images.githubusercontent.com/25035182/31616805-f2b565b4-b28d-11e7-9f46-3e5af6874e0a.png)
****
