### ISSUE TITLE
E-Mail service

### ISSUE THREAD

**Issue by Bouabidi** [h-da/geli#217]
Hi,
I have a problem with my Email service.
i have installed Geli-platform on my laptop und would like to use it locally.

the setting of my email service is:

export default {
  // Secret key for JWT signing and encryption
  secret: process.env.SECRET || 'notSoSecret234oi23o423ooqnafsnaaslfj',

  // BaseUrl for Webfrontend
  baseurl: process.env.BASEURL || 'http://localhost:4200',

  // Database connection information
  database: `mongodb://${process.env.DB_HOST || 'localhost'}:27017`,

  // Setting port for server
  port: process.env.PORT || 3030,

  // Email configuration
  // for provider see https://nodemailer.com/smtp/well-known/
  // Use either Provider or SMTPServer/Port
  mailProvider: process.env.MAILPROVIDER || 'debugmail.io',
  mailSMTPServer: process.env.MAILSMTPSERVER || undefined,
  mailSMTPPort: process.env.MAILSMTPPORT || 25,
  mailAuth: {
    user: process.env.MAILUSER || 'my email used by debugmail.io ',
    pass: process.env.MAILPASS || 'my password'
  },
  mailSender: process.env.MAILSENDER || 'no-reply@geli.edu',
  teacherMailRegex: process.env.TEACHER_MAIL_REGEX || '@h-da.de$',
};

i get this message

![error](https://user-images.githubusercontent.com/16801135/31512121-216f7e0a-af8a-11e7-94f5-c391cd2d9899.png)

and in my terminal : 
Error
api_1           |     at new HttpError (/usr/src/api/node_modules/routing-controllers/http-error/HttpError.js:27:23)
api_1           |     at User_1.User.findOne.then (/usr/src/api/build/src/controllers/AuthController.js:34:23)
api_1           |     at process._tickCallback (internal/process/next_tick.js:109:7)

thx

**Comment by grosspersky** [comment]
For security reasons at the moment you can only register as a teacher if you have a mail address ending with ``@h-da``.

To disable this functionality just change the regex in your config:
teacherMailRegex: process.env.TEACHER_MAIL_REGEX || '@h-da.de$',

**Comment by khase** [comment]
I have added the Var TEACHER_MAIL_REGEX=@h-da.de$ to our servers config.
We should definitly change this default to something like '$' to make it optional

**Comment by Bouabidi** [comment]
Thank you for your feedback.

**Comment by aeimer** [comment]
@Bouabidi does it works now? If yes, please close the ticket :)
