### ISSUE TITLE
insert data set

### ISSUE THREAD

**Issue by Bouabidi** [h-da/geli#230]
# User Story

### I want: 
insert some student data in my data base

123456 | student1 | student1 | student1@test.com
654321 | student2 | student2 | student2@test.com
345678 | student3 | student3 | student3@test.com
987654 | student4 | student4 | student4@test.com

### so that:
i can test the functionalities 

## Storypoints:
i became the following failure 
![error](https://user-images.githubusercontent.com/16801135/31765730-b18fa0ec-b4c5-11e7-8e6e-01981a201b84.png)

**Comment by khase** [comment]
Execute `npm run load:fixtures` in your api to load some predefined Fixtures
-> https://github.com/h-da/geli/blob/develop/api/fixtures/userFixtures.ts

**Comment by d89** [comment]
Closing this issue, please feel free to reopen if @khase's suggestion doesn't fix your issue.
