### ISSUE TITLE
Implement progress interface consistently for tasks

### ISSUE THREAD

**Issue by grosspersky** [h-da/geli#232]
# User Story

### As a: 
student

### I want:
to see my saved task units even after a page reload

### so that:
i can directly see my last results.

## Acceptance criteria:
- [x] task unit progress is saved for wrong answers with done = 0
- [x] answered task (progress object) is displayed

## Additional info:
The progress should be saved for all hits of the submit button and should be loaded when viewing the course later on

**Comment by d89** [comment]
Currently can't review this because of #451

**Comment by d89** [comment]
Awesome 👍
