### ISSUE TITLE
Add about page to the start page

### ISSUE THREAD

**Issue by PatrickSkowronek** [h-da/geli#237]
# User Story

### As a: 
User

### I want:
to look at the About page, without login in

### so that:
I can check what is geli or other information

## Acceptance criteria:

~- [ ] add footer or a box for the link to the about page~
or
- [x] add the menu button to the start page

**Comment by felixbrucker** [comment]
It was collectively decided to go with a menu toggle instead of a footer as it looks better and gives a more continuous user experience as the menu toggle is used later on as well.

**Comment by d89** [comment]
Looks great 👍
