### ISSUE TITLE
Add better error messages for registration page

### ISSUE THREAD

**Issue by PatrickSkowronek** [h-da/geli#240]
# User Story

### As a: 
User

### I want:
more feedback when a student creates his account

### so that:
the student knows what is wrong with the input data

## Acceptance criteria:
- [x]  show individual error messages that describe what exactly is wrong. Not one general error message.
- [x] password should be at least 8 letters and one character that is not a letter.

**Comment by aeimer** [comment]
related to #80

**Comment by d89** [comment]
Would be great if a teacher that wants to register with a non "@h-da.de" mail address would get a hint.

**Comment by d89** [comment]
Great 👍
