### ISSUE TITLE
Add tooltips for input fields

### ISSUE THREAD

**Issue by PatrickSkowronek** [h-da/geli#241]
# User Story

### As a: 
User

### I want:
i can not tell the purpose of all text fields or input types
### so that:
we need to find a solution to tell the user what does this input field

## Acceptance criteria:
- [ ] Implement a toolbox solution that a user hover over a Text field he gets a purpose of the input field

## Additional info:
May use css style https://www.w3schools.com/css/css_tooltip.asp
Or use angular material https://material.angularjs.org/latest/demo/tooltip

**Comment by lukaskorte** [comment]
This issue does not make sense. We already have a label for the input elements. The additional tooltip is unnecessary and irritating:
![screenshot from 2017-11-01 22-14-50](https://user-images.githubusercontent.com/3072741/32298329-5665b660-bf52-11e7-94ea-aeadd5048b0a.png)
