### ISSUE TITLE
Fixed offset of unit type in manage content tab

### ISSUE THREAD

**Issue by PatrickSkowronek** [h-da/geli#243]
![243](https://user-images.githubusercontent.com/32745673/31854304-e4cc7ca0-b696-11e7-9694-0bb932128889.jpg)
In the table of manage content the types of a Unit have all a different offset. This should be one Offset for all Types. As discussed this cloud be a css problem.

**Comment by aeimer** [comment]
Duplicate of #214

**Comment by d89** [comment]
Awesome, looks good!
