### ISSUE TITLE
No need to confirm the Matrikelnummer in the Register view

### ISSUE THREAD

**Issue by micpah** [h-da/geli#244]
# User Story

### As a: 
user

### I want:
to have only one field for the _Matrikelnummer_ in the Register view

### so that:
I don't need to enter the same (visible) value twice.

## Acceptance criteria:

- [x] Only one field for the _Matrikelnummer_ in the Register view
- [x] No confirmation of the _Matrikelnummer_ anymore

## Additional info:
This was discussed (and also already greenlighted by Prof. Trapp and @d89) during our meeting last Thursday.

**Comment by micpah** [comment]
Changed labels because there actually was a bug: you could fill out two different numbers and still got registered successfully. So there was no validation i.e. check whether the two numbers match.
This bug is fixed since the second Matrikelnummer field ("Confirm Matrikelnummer") is removed (as requested by this issue).

**Comment by d89** [comment]
Looks great!
