### ISSUE TITLE
Improve markdown unit type

### ISSUE THREAD

**Issue by d89** [h-da/geli#247]
Please improve the visualization of markdown input:

![image](https://user-images.githubusercontent.com/423154/31865531-25f54002-b770-11e7-9602-23730006b017.png)

- [x] Description and Name should be on the same level (same holds true for all the other content types - please fix this for all of 'em)
- [x] The Info/Help-Text needs more padding
- [x] A live preview would be great!
- [x] style markdown in a nother way as normal html (e.g. h1)
- [x] fullscreen edit mode
- [x] (optional) use better texteditor

**Comment by d89** [comment]
Go from "Preview"-mode to full screen, then change something in fullscreen mode. When you now close the fullscreen mode, the change is lost.

Apart from that: Awesome solution - looks great and feels great.

**Comment by aeimer** [comment]
No it shoulnd! it's just not applied to the small preview, in the edit tab it is there ;)

**Comment by d89** [comment]
Nope, even when I switch over to the edit tab once I left fullscreen, the old stuff is still there.

**Comment by aeimer** [comment]
No it appers! You may gave to click into the field...

**Comment by d89** [comment]
Ah - yes. But only after I clicked. Can you fix that?

**Comment by aeimer** [comment]
uff, that should be angular related. It will try, but not today...

**Comment by aeimer** [comment]
Couldn't fix this issue. I would like to close this Issue and create a bug-issue for this specific problem. @d89 do you agree?

**Comment by aeimer** [comment]
@felixbrucker wasn't able to fix it. Will close ticket and create new Bug-Issue
