### ISSUE TITLE
Use livereload while development

### ISSUE THREAD

**Issue by aeimer** [h-da/geli#253]
# User Story

### As a: 
Developer

### I want:
to use [livereload](https://www.npmjs.com/package/livereload)

### so that:
I don't have to reload the page manually on an update, changes get injected instead a whole page reload and so I am faster.

## Acceptance criteria:
- [ ] use livereload
- [ ] port for live reload is forwarded so the browser can access it
- [ ] livereload is hooked into all relevant gulp-tasks

## Additional info:
- https://www.npmjs.com/package/livereload
- https://www.npmjs.com/package/gulp-livereload

**Comment by grosspersky** [comment]
Why should we need this? Angular already rebuilds automatically if a file is changed and reloads the browser when the compilation is complete.

**Comment by aeimer** [comment]
You may be right, but it reloads the the WHOLE Website! Livereload injects the code right into the website. This way styling a website is much more efficient. In fact I don't know if webpack and livereload can work together...

**Comment by lukaskorte** [comment]
This will not work with Angular CLI, closing.
