### ISSUE TITLE
Password reset does not work as expected

### ISSUE THREAD

**Issue by khase** [h-da/geli#259]
If i wan't to reset my passwort on the Staging System nothing happens.

**Comment by PatrickSkowronek** [comment]
After creating a student account, the back to start page button does nothing!

**Comment by khase** [comment]
fixed by #268 
closed

**Comment by d89** [comment]
Password reset did not work for me. I received a mail with a link where I expected to be able to put a new password. However, I was just prompted with a normal login form and no reset possibility.

**Comment by d89** [comment]
I tried again - now I end up on the proper password reset page but receive the following error:

`{"name":"HttpError","message":"could not reset users password","stack":"Error\n    at new HttpError (/usr/src/app/node_modules/routing-controllers/http-error/HttpError.js:27:23)\n    at User_1.User.findOne.then (/usr/src/app/controllers/AuthController.js:75:23)\n    at process._tickCallback (internal/process/next_tick.js:109:7)"}`

**Comment by d89** [comment]
And on top of that: Please apply the same hint for the expected password strength that is also displayed on the registration page.

**Comment by khase** [comment]
This is a problem cused by the basic auth which somehow always redirects to the login page.

To reset your password on our staging system you first need to authenticate the basic out in a Browser tab and then copy the link sent to you by Mail inside the tab you've just authorized.

**Comment by khase** [comment]
closed since this is a problem with our staging setup
