### ISSUE TITLE
Student: Download selected units

### ISSUE THREAD

**Issue by utetrapp** [h-da/geli#260]
## Acceptance criteria:

- [x] select all/unselect all
- [x] select one or more lectures or reasonable units (files, videos, markdown) in the current course
- [x] download a zip-file with an ordered list of all selected units
show progress (zip file generation progress): Is not possible 
- [x] implement a hierarchy folder structure, which display the folder <number>. <lectureName>/<number>. <unitName>
- [x] add a delete logic
- [x] add a cache logic
- [x] remove special character and allow only character and numbers
- [x] implement a zip size limit
- [x] add a proper styling
- [x] show items that were too large for including in the zip file and offer a seperate download (non-zipped)

**Comment by PatrickSkowronek** [comment]
Added more features requests

**Comment by d89** [comment]
When I try to download the FWE course (https://staging.geli.fbi.h-da.de/course/597df6d5b7a9c0000616637f), this is what happens. The download popup does not open.

![image](https://user-images.githubusercontent.com/423154/35198687-e8402f86-fef2-11e7-82c5-a06bc3ad46af.png)

Another notice: When I try to manually download a file that is too big, It doesn't work. Instead, I see "Failed - No file" in Chrome. No javascript error or the like.

![image](https://user-images.githubusercontent.com/423154/35198738-ac9e33a0-fef3-11e7-9f70-f8335acad2dc.png)

**Comment by PatrickSkowronek** [comment]
should be closed through #495

**Comment by d89** [comment]
Sorry, Downloading of large files does not work.

Course: https://staging.geli.fbi.h-da.de/course/5aca016b458a870008f23069

![image](https://user-images.githubusercontent.com/423154/38467172-d4e3408a-3b34-11e8-9324-c521579baf0d.png)

**Comment by d89** [comment]
Seems like the whole Download-feature is broken right now:

![image](https://user-images.githubusercontent.com/423154/38467180-f2c7e63c-3b34-11e8-8882-a2be45999d40.png)

**Comment by d89** [comment]
Works great, except one tiny edge case. Press "Download" without selecting any unit. You will correctly receive an error toast telling you to select units. Afterwards, it's not possible any longer to download units.

![image](https://user-images.githubusercontent.com/423154/38958001-4629ac82-435c-11e8-8ea1-46e44aa7bd07.png)
