### ISSUE TITLE
file upload UI/UX

### ISSUE THREAD

**Issue by shelmz** [h-da/geli#269]
# User Story

### As a: 

Teacher

### I want:

a simple intuitive way to upload files

### so that:

- it works distraction free and gives feedback on successful file upload
- it accepts a bunch of popular file formats

## Acceptance criteria:

- [x] usability review
- [x] restyling

## Additional ideas:

- [x] a function to import an external .csv file with infos eg. about attending course members (already done with #41)

**Comment by d89** [comment]
Looks great 👍 

But somehow, it doesn't really work, at least not on the staging system. Some things I noticed when playing around with it for some time:

- This is what happens, after I uploaded a file: `{"name":"ValidationError","message":"file validation failed: fileUnitType: Path `fileUnitType` is required.","stack":"ValidationError: file validation failed: fileUnitType: Path `fileUnitType` is required.\n    at new ValidationError (/usr/src/app/node_modules/mongoose/lib/error/validation.js:28:11)\n    at model.Document.invalidate (/usr/src/app/node_modules/mongoose/lib/document.js:1666:32)\n    at /usr/src/app/node_modules/mongoose/lib/document.js:1538:17\n    at validate (/usr/src/app/node_modules/mongoose/lib/schematype.js:784:7)\n    at /usr/src/app/node_modules/mongoose/lib/schematype.js:829:11\n    at Array.forEach (<anonymous>)\n    at SchemaString.SchemaType.doValidate (/usr/src/app/node_modules/mongoose/lib/schematype.js:789:19)\n    at /usr/src/app/node_modules/mongoose/lib/document.js:1536:9\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)","errors":{"fileUnitType":{"message":"Path `fileUnitType` is required.","name":"ValidatorError","properties":{"type":"required","message":"Path `{PATH}` is required.","path":"fileUnitType"},"kind":"required","path":"fileUnitType","$isValidatorError":true}},"_message":"file validation failed"}`
- Once I hit "cancel upload" I cannot continue with the next file when I press "Upload and save" again
- I can add the same file multiple times.
- The already uploaded files are shown with 0,0B: 
![image](https://user-images.githubusercontent.com/423154/34535478-357cb9e8-f0c2-11e7-8948-3df8f73ab716.png)
- Deleting existing files doesn't work and shows the same error as above. Could we delete the files right away without having to press the "upload & save" button again?

This is the course I was testing it with: https://staging.geli.fbi.h-da.de/course/5953e5b868f8c80007898785/edit

**Comment by PatrickSkowronek** [comment]
This error is occurring on the current develop

`TypeError: this.model.files is undefined
Stack trace:
FileUnitFormComponent.prototype.checkSave@webpack-internal:///../../../../../src/app/unit/unit-form/file-unit-form/file-unit-form.component.ts:156:20
View_FileUnitFormComponent_0/<@ng:///UnitFormModule/FileUnitFormComponent.ngfactory.js:149:21
debugUpdateDirectives@webpack-internal:///../../../core/esm5/core.js:14887:12
checkAndUpdateView@webpack-internal:///../../../core/esm5/core.js:14034:5
callViewAction@webpack-internal:///../../../core/esm5/core.js:14385:21
execComponentViewsAction@webpack-internal:///../../../core/esm5/core.js:14317:13
checkAndUpdateView@webpack-internal:///../../../core/esm5/core.js:14040:5
callViewAction@webpack-internal:///../../../core/esm5/core.js:14385:21
execEmbeddedViewsAction@webpack-internal:///../../../core/esm5/core.js:14343:17
checkAndUpdateView@webpack-internal:///../../../core/esm5/core.js:14035:5
callViewAction@webpack-internal:///../../../core/esm5/core.js:14385:21
execEmbeddedViewsAction@webpack-internal:///../../../core/esm5/core.js:14343:17
checkAndUpdateView@webpack-internal:///../../../core/esm5/core.js:14035:5
callViewAction@webpack-internal:///../../../core/esm5/core.js:14385:21
execComponentViewsAction@webpack-internal:///../../../core/esm5/core.js:14317:13
checkAndUpdateView@webpack-internal:///../../../core/esm5/core.js:14040:5
callViewAction@webpack-internal:///../../../core/esm5/core.js:14385:21
execEmbeddedViewsAction@webpack-internal:///../../../core/esm5/core.js:14343:17
checkAndUpdateView@webpack-internal:///../../../core/esm5/core.js:14035:5
callViewAction@webpack-internal:///../../../core/esm5/core.js:14385:21
execEmbeddedViewsAction@webpack-internal:///../../../core/esm5/core.js:14343:17
checkAndUpdateView@webpack-internal:///../../../core/esm5/core.js:14035:5
callViewAction@webpack-internal:///../../../core/esm5/core.js:14385:21
execEmbeddedViewsAction@webpack-internal:///../../../core/esm5/core.js:14343:17
checkAndUpdateView@webpack-internal:///../../../core/esm5/core.js:14035:5
callViewAction@webpack-internal:///../../../core/esm5/core.js:14385:21
execEmbeddedViewsAction@webpack-internal:///../../../core/esm5/core.js:14343:17
checkAndUpdateView@webpack-internal:///../../../core/esm5/core.js:14035:5
callViewAction@webpack-internal:///../../../core/esm5/core.js:14385:21
execComponentViewsAction@webpack-internal:///../../../core/esm5/core.js:14317:13
checkAndUpdateView@webpack-internal:///../../../core/esm5/core.js:14040:5
callViewAction@webpack-internal:///../../../core/esm5/core.js:14385:21
execComponentViewsAction@webpack-internal:///../../../core/esm5/core.js:14317:13
checkAndUpdateView@webpack-internal:///../../../core/esm5/core.js:14040:5
callViewAction@webpack-internal:///../../../core/esm5/core.js:14385:21
execEmbeddedViewsAction@webpack-internal:///../../../core/esm5/core.js:14343:17
checkAndUpdateView@webpack-internal:///../../../core/esm5/core.js:14035:5
callViewAction@webpack-internal:///../../../core/esm5/core.js:14385:21
execComponentViewsAction@webpack-internal:///../../../core/esm5/core.js:14317:13
checkAndUpdateView@webpack-internal:///../../../core/esm5/core.js:14040:5
callWithDebugContext@webpack-internal:///../../../core/esm5/core.js:15288:39
debugCheckAndUpdateView@webpack-internal:///../../../core/esm5/core.js:14825:12
ViewRef_.prototype.detectChanges@webpack-internal:///../../../core/esm5/core.js:11802:9
ApplicationRef.prototype.tick/<@webpack-internal:///../../../core/esm5/core.js:6110:58
ApplicationRef.prototype.tick@webpack-internal:///../../../core/esm5/core.js:6110:13
next/<@webpack-internal:///../../../core/esm5/core.js:5943:99
ZoneDelegate.prototype.invoke@webpack-internal:///../../../../zone.js/dist/zone.js:392:17
onInvoke@webpack-internal:///../../../core/esm5/core.js:4953:24
ZoneDelegate.prototype.invoke@webpack-internal:///../../../../zone.js/dist/zone.js:391:17
Zone.prototype.run@webpack-internal:///../../../../zone.js/dist/zone.js:142:24
NgZone.prototype.run@webpack-internal:///../../../core/esm5/core.js:4770:54
next@webpack-internal:///../../../core/esm5/core.js:5943:69
EventEmitter.prototype.subscribe/schedulerFn<@webpack-internal:///../../../core/esm5/core.js:4539:36
SafeSubscriber.prototype.__tryOrUnsub@webpack-internal:///../../../../rxjs/_esm5/Subscriber.js:244:13
SafeSubscriber.prototype.next@webpack-internal:///../../../../rxjs/_esm5/Subscriber.js:191:17
Subscriber.prototype._next@webpack-internal:///../../../../rxjs/_esm5/Subscriber.js:132:9
Subscriber.prototype.next@webpack-internal:///../../../../rxjs/_esm5/Subscriber.js:96:13
Subject.prototype.next@webpack-internal:///../../../../rxjs/_esm5/Subject.js:65:17
EventEmitter.prototype.emit@webpack-internal:///../../../core/esm5/core.js:4519:24
checkStable@webpack-internal:///../../../core/esm5/core.js:4918:13
onLeave@webpack-internal:///../../../core/esm5/core.js:4997:5
onInvokeTask@webpack-internal:///../../../core/esm5/core.js:4947:17
ZoneDelegate.prototype.invokeTask@webpack-internal:///../../../../zone.js/dist/zone.js:424:17
Zone.prototype.runTask@webpack-internal:///../../../../zone.js/dist/zone.js:192:28
ZoneTask.invokeTask@webpack-internal:///../../../../zone.js/dist/zone.js:499:24
ZoneTask/this.invoke@webpack-internal:///../../../../zone.js/dist/zone.js:488:28
timer@webpack-internal:///../../../../zone.js/dist/zone.js:2040:17`

**Comment by aeimer** [comment]
I think we can close this ticket. We should add a new `BUG` Ticket

**Comment by d89** [comment]
Ok, this looks great now! I have 2 remarks:

* When I cancel the upload of one of the files and try to restart it by clicking the "Upload and save" button, it doesn't continue the upload with the next file but instead gives me this error: `SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at e.fileUploader.onCompleteItem (https://staging.geli.fbi.h-da.de/1.8ab5afb968c03f95c598.chunk.js:1:108940)
    at e._onCompleteItem (https://staging.geli.fbi.h-da.de/main.77e6fbfc850bb34e8981.bundle.js:1:331918)
    at XMLHttpRequest.i.onabort [as __zone_symbol__ON_PROPERTYabort] (https://staging.geli.fbi.h-da.de/main.77e6fbfc850bb34e8981.bundle.js:1:333562)
    at XMLHttpRequest.x (https://staging.geli.fbi.h-da.de/polyfills.46ccb38dadfae6ca51a8.bundle.js:1:62751)
    at XMLHttpRequest.r (https://staging.geli.fbi.h-da.de/main.77e6fbfc850bb34e8981.bundle.js:1:3004524)
    at t.invokeTask (https://staging.geli.fbi.h-da.de/polyfills.46ccb38dadfae6ca51a8.bundle.js:1:54448)
    at Object.onInvokeTask (https://staging.geli.fbi.h-da.de/main.77e6fbfc850bb34e8981.bundle.js:1:1010728)
    at t.invokeTask (https://staging.geli.fbi.h-da.de/polyfills.46ccb38dadfae6ca51a8.bundle.js:1:54369)
    at r.runTask (https://staging.geli.fbi.h-da.de/polyfills.46ccb38dadfae6ca51a8.bundle.js:1:49626)
    at e.invokeTask [as invoke] (https://staging.geli.fbi.h-da.de/polyfills.46ccb38dadfae6ca51a8.bundle.js:1:55558)
    at v (https://staging.geli.fbi.h-da.de/polyfills.46ccb38dadfae6ca51a8.bundle.js:1:43941)
    at XMLHttpRequest.d (https://staging.geli.fbi.h-da.de/polyfills.46ccb38dadfae6ca51a8.bundle.js:1:44174)
    at e.f [as cancelFn] (https://staging.geli.fbi.h-da.de/polyfills.46ccb38dadfae6ca51a8.bundle.js:1:75850)
    at t.cancelTask (https://staging.geli.fbi.h-da.de/polyfills.46ccb38dadfae6ca51a8.bundle.js:1:54672)
    at Object.onCancelTask (https://staging.geli.fbi.h-da.de/polyfills.46ccb38dadfae6ca51a8.bundle.js:1:51486)
    at t.cancelTask (https://staging.geli.fbi.h-da.de/polyfills.46ccb38dadfae6ca51a8.bundle.js:1:54546)
    at r.cancelTask (https://staging.geli.fbi.h-da.de/polyfills.46ccb38dadfae6ca51a8.bundle.js:1:50907)
    at https://staging.geli.fbi.h-da.de/polyfills.46ccb38dadfae6ca51a8.bundle.js:1:76621
    at XMLHttpRequest.o.(anonymous function) [as abort] (https://staging.geli.fbi.h-da.de/polyfills.46ccb38dadfae6ca51a8.bundle.js:1:40051)
    at e.cancelItem (https://staging.geli.fbi.h-da.de/main.77e6fbfc850bb34e8981.bundle.js:1:329665)
    at e.cancel (https://staging.geli.fbi.h-da.de/main.77e6fbfc850bb34e8981.bundle.js:1:188034)
    at Object.handleEvent (https://staging.geli.fbi.h-da.de/1.8ab5afb968c03f95c598.chunk.js:1:31542)
    at Object.handleEvent (https://staging.geli.fbi.h-da.de/main.77e6fbfc850bb34e8981.bundle.js:1:968630)
    at Object.handleEvent (https://staging.geli.fbi.h-da.de/main.77e6fbfc850bb34e8981.bundle.js:1:980326)
    at ze (https://staging.geli.fbi.h-da.de/main.77e6fbfc850bb34e8981.bundle.js:1:948581)
    at https://staging.geli.fbi.h-da.de/main.77e6fbfc850bb34e8981.bundle.js:1:954190
    at HTMLButtonElement.<anonymous> (https://staging.geli.fbi.h-da.de/main.77e6fbfc850bb34e8981.bundle.js:1:1214489)
    at HTMLButtonElement.r (https://staging.geli.fbi.h-da.de/main.77e6fbfc850bb34e8981.bundle.js:1:3004524)
    at t.invokeTask (https://staging.geli.fbi.h-da.de/polyfills.46ccb38dadfae6ca51a8.bundle.js:1:54448)
    at Object.onInvokeTask (https://staging.geli.fbi.h-da.de/main.77e6fbfc850bb34e8981.bundle.js:1:1010728)
    at t.invokeTask (https://staging.geli.fbi.h-da.de/polyfills.46ccb38dadfae6ca51a8.bundle.js:1:54369)
    at r.runTask (https://staging.geli.fbi.h-da.de/polyfills.46ccb38dadfae6ca51a8.bundle.js:1:49626)
    at e.invokeTask [as invoke] (https://staging.geli.fbi.h-da.de/polyfills.46ccb38dadfae6ca51a8.bundle.js:1:55558)
    at v (https://staging.geli.fbi.h-da.de/polyfills.46ccb38dadfae6ca51a8.bundle.js:1:43941)
    at HTMLButtonElement.d (https://staging.geli.fbi.h-da.de/polyfills.46ccb38dadfae6ca51a8.bundle.js:1:44174)
e.(anonymous function) @ console.js:32
e.handleError @ raven-error-handler.service.ts:23
next @ core.js.pre-build-optimizer.js:5503
t.object.i @ core.js.pre-build-optimizer.js:4342
t.__tryOrUnsub @ Subscriber.js.pre-build-optimizer.js:239
t.next @ Subscriber.js.pre-build-optimizer.js:186
t._next @ Subscriber.js.pre-build-optimizer.js:127
t.next @ Subscriber.js.pre-build-optimizer.js:91
t.next @ Subject.js.pre-build-optimizer.js:56
t.emit @ core.js.pre-build-optimizer.js:4322
(anonymous) @ core.js.pre-build-optimizer.js:4778
t.invoke @ zone.js:392
r.run @ zone.js:142
e.runOutsideAngular @ core.js.pre-build-optimizer.js:4704
onHandleError @ core.js.pre-build-optimizer.js:4778
t.handleError @ zone.js:396
r.runTask @ zone.js:195
e.invokeTask @ zone.js:499
v @ zone.js:1540
d @ zone.js:1566
f @ zone.js:2943
t.cancelTask @ zone.js:436
onCancelTask @ zone.js:305
t.cancelTask @ zone.js:430
r.cancelTask @ zone.js:270
(anonymous) @ zone.js:2980
o.(anonymous function) @ zone.js:1366
e.cancelItem @ file-uploader.class.js.pre-build-optimizer.js:112
e.cancel @ file-item.class.js.pre-build-optimizer.js:38
(anonymous) @ upload-form.component.ngfactory.js.pre-build-optimizer.js:28
handleEvent @ core.js.pre-build-optimizer.js:13582
handleEvent @ core.js.pre-build-optimizer.js:14314
ze @ core.js.pre-build-optimizer.js:9995
(anonymous) @ core.js.pre-build-optimizer.js:10616
(anonymous) @ platform-browser.js.pre-build-optimizer.js:2628
r @ raven.js:351
t.invokeTask @ zone.js:425
onInvokeTask @ core.js.pre-build-optimizer.js:4747
t.invokeTask @ zone.js:424
r.runTask @ zone.js:192
e.invokeTask @ zone.js:499
v @ zone.js:1540
d @ zone.js:1566
XMLHttpRequest.send (async)
n @ zone.js:2933
t.scheduleTask @ zone.js:411
onScheduleTask @ zone.js:301
t.scheduleTask @ zone.js:405
r.scheduleTask @ zone.js:236
r.scheduleMacroTask @ zone.js:259
(anonymous) @ zone.js:2966
o.(anonymous function) @ zone.js:1366
(anonymous) @ raven.js:1223
e._xhrTransport @ file-uploader.class.js.pre-build-optimizer.js:302
e.uploadItem @ file-uploader.class.js.pre-build-optimizer.js:105
n.uploadNextItem @ upload-form.component.ts:127
(anonymous) @ file-unit-form.component.ts:102
(anonymous) @ file-unit-form.component.ts.pre-build-optimizer.js:39
(anonymous) @ file-unit-form.component.ts.pre-build-optimizer.js:20
(anonymous) @ file-unit-form.component.ts.pre-build-optimizer.js:14
t @ zone.js:890
En @ file-unit-form.component.ts.pre-build-optimizer.js:10
n.uploadAll @ file-unit-form.component.ts.pre-build-optimizer.js:107
(anonymous) @ file-unit-form.component.ngfactory.js.pre-build-optimizer.js:45
handleEvent @ core.js.pre-build-optimizer.js:13582
handleEvent @ core.js.pre-build-optimizer.js:14314
ze @ core.js.pre-build-optimizer.js:9995
(anonymous) @ core.js.pre-build-optimizer.js:10616
(anonymous) @ platform-browser.js.pre-build-optimizer.js:2628
r @ raven.js:351
t.invokeTask @ zone.js:425
onInvokeTask @ core.js.pre-build-optimizer.js:4747
t.invokeTask @ zone.js:424
r.runTask @ zone.js:192
e.invokeTask @ zone.js:499
v @ zone.js:1540
d @ zone.js:1566`
* A warning would be nice when I added the same file twice.

Other than that: awesome 👍

**Comment by d89** [comment]
And another remark: When I want to upload a video, I can select files that are not videos. After doing that, it is not telling me that I did something wrong.

![image](https://user-images.githubusercontent.com/423154/35198160-fa735e10-feea-11e7-8773-10b31238a1f3.png)

**Comment by aeimer** [comment]
This will be done by my mediamanager remake #265

**Comment by aeimer** [comment]
#448 should solve all these problems. Will close
#380 is the right ticket for restart upload issues
