### ISSUE TITLE
🐛 BUG: Teachers report board shows wrong data

### ISSUE THREAD

**Issue by khase** [h-da/geli#273]
The Teachers Report-Board will display a unit as `Done` if only one Student has  really done it.

![image](https://user-images.githubusercontent.com/26968077/32136501-f6589120-bc0e-11e7-8ad9-803bed3bfe04.png)

**Comment by aeimer** [comment]
@grosspersky is this bug solved with your recent refactores?

**Comment by grosspersky** [comment]
Yes, this has been solved with the refactoring.
