### ISSUE TITLE
List the last visited course at first in the "my courses" view

### ISSUE THREAD

**Issue by d89** [h-da/geli#276]
# User Story

### As a: 

Student

### I want:

to see the course tile first, that I last visited

### so that:

I can directly jump right into where I left off.

## Additional info:
after discussing with david both categories are sorted by bottles in the teacher's section

**Comment by PatrickSkowronek** [comment]
As I discussed all student courses should be sorted by last visit.

**Comment by d89** [comment]
Lookin' good 👍
