### ISSUE TITLE
Refactor (multiple choice) tasks

### ISSUE THREAD

**Issue by micpah** [h-da/geli#284]
## Acceptance criteria (for teacher's view):

- [x] Buttons (Add, +, -) are rearranged
- [x] Localization is consistent (i.e. everything in English for now)
- [x] Template for task is added
- [x] Each answer is removable

## Acceptance criteria (for student's view):

- [x] Title and description are properly displayed

## Additional info:
Related issues: #162, #350

**Comment by d89** [comment]
Looks way better! I still have a tiny little enhancement wish - could you please style the checkmarks position and padding?

![image](https://user-images.githubusercontent.com/423154/33043564-2f70cfb0-ce46-11e7-88af-ea1ed3fa964d.png)

**Comment by micpah** [comment]
@d89 Does this look good?
![image](https://user-images.githubusercontent.com/9725083/33049568-0becfc24-ce61-11e7-95f2-e8d03b9a24e7.png)

**Comment by d89** [comment]
Oh yes 👍

**Comment by d89** [comment]
Looks great alltogether now 👍 !

**Comment by d89** [comment]
Added in the session on 2017-11-30:

- [ ] use "trash bins" instead of a "-" sign to remove answers / questions
- [ ] Start with 2 answers and 1 question right away. On top: Whenever I add a new question, 2 answers should be added with it.

**Comment by d89** [comment]
Awesome 👍
