### ISSUE TITLE
🐛 BUG: Better error/validation handling

### ISSUE THREAD

**Issue by OliverNeff** [h-da/geli#299]
# User Story
Technical error messages should not send directly to user.
For example a user could not know what a duplicate key error message ist. 
It should be shown for user as 

    Course could not created, because course exists. 

Furthermore validation errors should be shown directly within the input component like this: https://material.angular.io/components/input/overview#error-messages

**Comment by lukaskorte** [comment]
The basics are working now, but we should still:

[ ] Unify the error format returned by the API in case of Mongoose validation errors and custom validation errors
[ ] Unify the error handling in Angular for form validators and server side errors. The form also has to be invalidated in case of server side errors.
[ ] Error display should also be in some kind of shared component

**Comment by PatrickSkowronek** [comment]
This can be closed. The most part is done.

**Comment by d89** [comment]
It's currently broken - no error message at all on the staging system.

![no-error-frontend](https://user-images.githubusercontent.com/423154/38467069-44d39dce-3b33-11e8-9399-2ffa094c5e9a.PNG)

**Comment by PatrickSkowronek** [comment]
Blocked by #572
