### ISSUE TITLE
Trim every input in the registration form (except the password field)

### ISSUE THREAD

**Issue by d89** [h-da/geli#305]
kwt

**Comment by aeimer** [comment]
What exactly should be trimmed? Just whitespaces?

**Comment by d89** [comment]
In my opinion, yes. What else would you like to trim?

**Comment by aeimer** [comment]
Following to eg PHP http://php.net/manual/de/function.trim.php we could also trim tabs, new lines etc

**Comment by felixbrucker** [comment]
this should be sufficient: https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/String/Trim

**Comment by d89** [comment]
perfect 👍
