### ISSUE TITLE
Matriculation number should be unique

### ISSUE THREAD

**Issue by d89** [h-da/geli#306]
It should not be possible to register with an already used matriculation number.

**Comment by grosspersky** [comment]
It isn't possible to register with an used matriculation number since this field is marked as unique in our model:
```
    uid: {
      type: String,
      lowercase: true,
      unique: true,
      sparse: true
    },
```
However we need to investigate why the frontend thinks the registration was completed with success even when no account was created in the database.

**Comment by d89** [comment]
fine 👍
