### ISSUE TITLE
Use the same badges in the course member section as we also use for "available courses / my courses"

### ISSUE THREAD

**Issue by d89** [h-da/geli#308]
Please use the same badges here:

![image](https://user-images.githubusercontent.com/423154/32386598-10b4065a-c0c2-11e7-8515-663b15a84488.png)

that we also used here:

![image](https://user-images.githubusercontent.com/423154/32386622-2209cf98-c0c2-11e7-84cf-7fab5e73e836.png)

**Comment by PatrickSkowronek** [comment]
Moved the badge in new component, but the css in course edit members moves the badge in a new line.

**Comment by d89** [comment]
great 👍
