### ISSUE TITLE
Introduce an "inactive" section on the course overview

### ISSUE THREAD

**Issue by d89** [h-da/geli#309]
In the dashboard:

![image](https://user-images.githubusercontent.com/423154/32386675-49f657d8-c0c2-11e7-9217-06ceebd93887.png)

as a teacher (and only as a teacher) i want to have an "inactive" section where the courses appear, that I am teacher of but are set to "inactive" so I can preview them in the frontend.

**Comment by d89** [comment]
I just created a course as a teacher and set it to "Course cannot be seen by students". Seems like it does not appear at all:

![image](https://user-images.githubusercontent.com/423154/33042980-037d8530-ce44-11e7-93f2-1285118d8e7e.png)

**Comment by PatrickSkowronek** [comment]
This is an issue with the toggle button #374 this will fix it

**Comment by PatrickSkowronek** [comment]
This was fixed with #374

**Comment by d89** [comment]
Perfect, looks good 👍
