### ISSUE TITLE
The field for the current password should be hidden in the "edit profile" section as admin

### ISSUE THREAD

**Issue by d89** [h-da/geli#310]
When I change the profile of another user as admin, I do not want to see the "password" field in the frontend ... because I don't know the current password.

**Comment by d89** [comment]
Wait what? Right now it looks like the possibility to change other users passwords as admin has been removed alltogether?

**Comment by grosspersky** [comment]
The final bugfix seems to be missing. Should be solved with #400

**Comment by d89** [comment]
okay 👍
