### ISSUE TITLE
Implement Teacher, Student, Admin and Tutor Dashboard

### ISSUE THREAD

**Issue by PatrickSkowronek** [h-da/geli#324]
Sofar there is a dashboard for Teacher, Student, Admin and Tutor which is not in use. There are Different usecases for each role. This ticket should describe the  requirements for each dashboard.

## Admin
- Manage Media
- Configuration of geli
- Configure roles of user
- Info for login screen
- General settings

## Student
- Show my last modify Course #276 
- Show sorted task by deadline
- Sort courses by semester
- Add calender to show deadlines of task
- Show badges on course card if there is an update

## Teacher
- Add inactive icon #309 
- Sort courses into semester

## Tutor 
Do we need this?

Please add more use cases or Ideas as comments.

**Comment by PatrickSkowronek** [comment]
##All
- Add search for courses

**Comment by khase** [comment]
##Tutor 

i dont Think we need a Tutor as a separate role. in my understanding a tutor is just a student who has administrative rights (maybe not all of them) for a specific course.

**Comment by d89** [comment]
Nice collection so far! 

**For the tutor-case:** A tutor should - in my opinion - be a normal teacher, so he can create katas and multiple choice questions, add material and see the progress. The only thing that a tutor normally shouldn't do is create new courses and add/remove students from courses. However, this doesn't require creating a new role for this use case. I would be fine with trusting in humanity, that tutors don't do what they shouldn't do.

**Apart from that:** As a teacher, I would like to see a little progress summary of my students and the upcoming deadlines aswell.

**Comment by grosspersky** [comment]
> Apart from that: As a teacher, I would like to see a little progress summary of my students and the upcoming deadlines aswell.

A progress summary was already mentioned in #45, but there is missing some specification for the data that should be accumulated. Maybe we can reuse this progress summary on the dashboard.

**Comment by utetrapp** [comment]
Good summary.
Admin: Backup? What is the difference of general settings and configuration of geli?
I'm sure as we use the system more and more, more ideas will come to our mind ;-)

**Comment by khase** [comment]
can this be closed?

**Comment by utetrapp** [comment]
yes
