### ISSUE TITLE
Implement drag and drop upload function

### ISSUE THREAD

**Issue by shelmz** [h-da/geli#337]
As a user I want to be able to drag files from file browser and drop it to upload it with a specific upload menu. 

Solution: something like at the examples on:
https://valor-software.com/ng2-file-upload/

**Comment by OliverNeff** [comment]
This look nice, I look after it, but is there not an issue in progress for a nice looking uploade button?

**Comment by grosspersky** [comment]
This is inclued in #435

**Comment by grosspersky** [comment]
![grafik](https://user-images.githubusercontent.com/11839276/34151771-af6158e4-e4ac-11e7-9ed8-b4c0d494c080.png)

**Comment by grosspersky** [comment]
Already implemented with #435
