### ISSUE TITLE
get {{user?.profile.firstName}} locally

### ISSUE THREAD

**Issue by Bouabidi** [h-da/geli#340]
# User Storya 
HI every one,

I created a virtual classroom on Geli-Plattfrom and I would like to implement a chat service on it.
I am using socket.io to implement that.

### As a: 
I want to send message : the messages seem be always send by the current user.

### I want:

get user?.profile.firstName in a local variable in my angular component so that I can concatenate the message send with the right sender than send it 

### so that:

Get the message with name of sender and not the name of the current user.

Thank you.

**Comment by khase** [comment]
Hi Bouabidi,

I do not exactly get your problem but to get informations of the local signed in user
just inject the `UserService` through your constructor
```typescript
constructor(
              public userService: UserService,
             .....) {
}
```
Now you can access the whole user object of the local user.
```typescript
this.userService.user.profile.firstName;
```

**Comment by Bouabidi** [comment]
Hi,
i have some thing like that 
```javascript
var socket = io('http://localhost:3030');

export class ClassroomDetailComponent implements OnInit {
  Current_user:any;
  users=[];
  constructor(
              private classroomService: ClassroomService,
              public  userService: UserService,
              private chatService:ChatService,
              private webrtc: WebrtcService,
              ) {
               }

  ngOnInit():void { 
    this.Current_user=this.userService.user.profile.firstName;  
    this.users.push(this.Current_user) ; 
    });
}
```
and than get all the users connected
```html
 <div *ngFor="let user of users">       
 <span>{{user}}</span>												   
 </div> 
```

**Comment by khase** [comment]
Okay, so u have the `users` array populated with the current user are you now asking how to get the other users?

**Comment by Bouabidi** [comment]
yes, in my users array i get always  only the current user and every time i log with an other user , the current user is added and not the new one .

**Comment by khase** [comment]
you can't find out which users are connected by the client side (at least not that easy or complete). this is a feature you need to implement on the serverside for your chatService.

**Comment by Bouabidi** [comment]
ok thanks for your help :)

**Comment by khase** [comment]
you're welcome (:
