### ISSUE TITLE
Stagin-System broken

### ISSUE THREAD

**Issue by khase** [h-da/geli#343]
The Staging System is totally broken:
 - No courses shown
 - Menue does not close
 - Pages just append to each other
 - .....

![image](https://user-images.githubusercontent.com/26968077/32734619-cf6543f2-c892-11e7-9f20-53212647d067.png)

**Comment by grosspersky** [comment]
Reverted latest merges to develop, seems to be working correct again.

**Comment by PatrickSkowronek** [comment]
Cloud reproduce this problem because a course doesn't had a courseAdmin.
