### ISSUE TITLE
Change right/wrong color style for tasks

### ISSUE THREAD

**Issue by khase** [h-da/geli#347]
If a Task contains multiple Questions the submit function does not validate correctly:
![image](https://user-images.githubusercontent.com/26968077/32779396-f15c55c6-c93d-11e7-97da-80d08753cad4.png)
![image](https://user-images.githubusercontent.com/26968077/32779417-0666fcbe-c93e-11e7-9b29-ad5229c6e8e2.png)
![image](https://user-images.githubusercontent.com/26968077/32779438-17c98878-c93e-11e7-994e-8d949059f1cd.png)
![image](https://user-images.githubusercontent.com/26968077/32779452-22607558-c93e-11e7-8bbe-b75fe17cab31.png)
![image](https://user-images.githubusercontent.com/26968077/32779468-2cc7b222-c93e-11e7-81b3-19f2ab7cc128.png)
![image](https://user-images.githubusercontent.com/26968077/32779482-3f2ce25c-c93e-11e7-8610-e8e6bb42688c.png)

**Comment by khase** [comment]
![image](https://user-images.githubusercontent.com/26968077/33373873-18b40476-d504-11e7-9f7b-419affb3b4d5.png)
while: 
![image](https://user-images.githubusercontent.com/26968077/33373907-38b9c6c0-d504-11e7-94b3-ffbf87a720fc.png)

**Comment by aeimer** [comment]
Wanted bahaviour:
-  correct answers always green
- wrong answers always red
- submit btn in primary color

**Comment by d89** [comment]
Great 👍
