### ISSUE TITLE
Implement validation to task unit

### ISSUE THREAD

**Issue by micpah** [h-da/geli#350]
# User Story

### As a:
teacher

### I want:
my tasks to be validated before saving and helpful messages if a task is not valid

### so that:
I don't save incomplete tasks.

## Acceptance criteria:
Every task unit requires...
- [x] a name
- [x] at least one task/question

Every task/question requires...
- [x] to be defined (also no empty string allowed)
- [x] at least two answers
- [x] at least one checked answer

Every answer requires...
- [x] to be defined (also no empty string allowed)

**Comment by d89** [comment]
looks good 👍
