### ISSUE TITLE
Profile edit mask displays the password fields twice

### ISSUE THREAD

**Issue by d89** [h-da/geli#370]
![image](https://user-images.githubusercontent.com/423154/33042076-e6b47f88-ce40-11e7-836b-34d1608ac18b.png)

Both "Current Password" and "Confirm Password" are listed twice.

**Comment by khase** [comment]
This bug has already been fixed but not merged yet -> pr #365

**Comment by khase** [comment]
closed by #363

**Comment by d89** [comment]
check 👍
