### ISSUE TITLE
Creating a course as a teacher causes duplicated parts of the frontend

### ISSUE THREAD

**Issue by d89** [h-da/geli#372]
When I hit "Create Course" as a teacher (not as admin - admin seems to be fine), I see this:

![image](https://user-images.githubusercontent.com/423154/33042788-60bb7e2e-ce43-11e7-98da-34bc0be5c035.png)

Seems like the UI is duplicated somehow underneath the view.

**Comment by khase** [comment]
This was a bug with the staging System due to the fact that some Courses had courseAdmins which didn't exist anymore

#closes

**Comment by d89** [comment]
Awesome 👍
