### ISSUE TITLE
Courses don't show up in frontend

### ISSUE THREAD

**Issue by d89** [h-da/geli#374]
The course "Fortgeschrittene Webentwicklung" is free for everyone, but still as I student I can't see it in the course listing of the dashboard. Why is that?

![image](https://user-images.githubusercontent.com/423154/33043759-c5af713e-ce46-11e7-93f8-6cce0844f777.png)

**Comment by OliverNeff** [comment]
Is the active flag set on true or false? The toggle button is set on "Course cannot be seen by students" or not?

**Comment by d89** [comment]
Isn't that shown by the screenshot?

**Comment by PatrickSkowronek** [comment]
The label of the toggle button is wrong and the text should not be changed

**Comment by OliverNeff** [comment]
@PatrickSkowronek That is what I mean, I think this button is just confusing.

**Comment by PatrickSkowronek** [comment]
@OliverNeff I know, this is the reason I changed it!

**Comment by d89** [comment]
Great, I can now fully understand the toggle switch 👍

**Comment by PatrickSkowronek** [comment]
What is wrong with it?

**Comment by d89** [comment]
Nothing, I mistakenly reopened the issue by acceident.
