### ISSUE TITLE
Refactor Fixtures/Tests

### ISSUE THREAD

**Issue by khase** [h-da/geli#395]
Fixtures: 
- [x] import *.course.json Files
- [x] assigne a random teacher as course.courseAdmin
- [x] assign up to n teachers as course.teacher
- [x] enroll up to m students to the course (and whitelist?)
- [x] create random progresses for a subset of students

Tests:
Provide a TestHelperClass to provide Functionality like:
- [x] getRandomAdmin()
- [x] getRandomTeacher()
- [x] getRandomStudent()
- [x] ???

**Comment by d89** [comment]
Assuming this is not reviewable, moving it to done.
