### ISSUE TITLE
Add Media Popup

### ISSUE THREAD

**Issue by aeimer** [h-da/geli#396]
# User Story

### As a: 
Student

### I want:
to have a nice clean popup which shows (if possible) media or file uploads

### so that:
I don't have to open a new Tab or Download the file I want to see

## Acceptance criteria:
- [ ] 

## Additional info:
- Images, Videos and PDFs should be displayed in a fullscreen popup
  - Images should have a zoom mode
- All other types stay downloadable, eg

**Comment by grosspersky** [comment]
Maybe this could be helpful:
https://github.com/themyth92/angular2-lightbox

**Comment by aeimer** [comment]
@grosspersky in general this is a cool thing, we could use it in #265 but here the gallery is a huge overkill.

**Comment by d89** [comment]
Looks great! Except for PDF files and videos (uploaded in "file upload" mode) there is no preview, like it is written in "additional info". This is however totally fine for me 👍

**Comment by aeimer** [comment]
I haven't tried it yet. But to be honest I think it won't work out of the box. 

But I will check this out.
