### ISSUE TITLE
Enhance free text mails

### ISSUE THREAD

**Issue by felixbrucker** [h-da/geli#408]
# User Story

### As a: 

teacher/admin

### I want:

- to be able to get mail reply's to my (teacher/admin) mail while the `from` is still the "geli" address
- to get notified about / receive other teacher/admins mails via automatic `cc`
- mail templates or a footer for starters and maybe subject prefix with some information about what and why the user received this mail
- a "select all" button to select/deselect all course members at once

## Acceptance criteria:
- [x] `reply to` my mail address
- [x] send mails to other teachers via `cc`
- [x] basic footer or a mail template and subject prefix
- [x] "select all" button to toggle all members

## Additional ideas:

- [x] use markdown editor and https://www.npmjs.com/package/nodemailer-markdown to automatically generate `text` and `html` mail bodies
- [x] jump to first editor line
- [x] set focus on subject line instead of bcc
- [x] add horizontal line to footer

**Comment by felixbrucker** [comment]
https://nodemailer.com/message/#routing-options

`replyTo` or `sender` can be used to deliver using one mail but show another (when replying)

**Comment by d89** [comment]
Wow! Great feature, in my tests everything worked out just as I expected. Awesome 👍 💯
