### ISSUE TITLE
Add students based on a csv-file

### ISSUE THREAD

**Issue by utetrapp** [h-da/geli#41]
# User Story

### As a: 
teacher

### I want:
add/asign students to a course based on a csv-file

### so that:
save time.

## Acceptance criteria:
- [x] expected format of the csv-file needs to be displayed to the user and validated accordingly before starting the import
- [x] CSV Import should be possible through the teacher's web interface (upload).

## Additional info:
Example of an CSV-File: 
[SauerTDoergeMuellerD_SS17_FortgeschritteneWebentwicklung_302566_Teilnehmer.zip](https://github.com/h-da/geli/files/994519/SauerTDoergeMuellerD_SS17_FortgeschritteneWebentwicklung_302566_Teilnehmer.zip)

As discussed in the meeting: We don't have the mail addresses of the students in this CSV file, so we might enroll students automatically to the course that register themselves with their matrikel number (#48) that we get from the CSV file upload. See #102 for a related task (mail whitelist)

**Comment by aeimer** [comment]
How shall the import work? Trough the frontend or via a backend-command?

**Comment by utetrapp** [comment]
Since the teachers should be able to administer their students by themselves, it will need a frontend.

**Comment by d89** [comment]
I uploaded a sample CSV file as the OBS provides it. Furthermore, I edited the issue accordingly to the discussion of todays meeting.

**Comment by khase** [comment]
implemented with pr #144
