### ISSUE TITLE
Button styling according to the "GELI Design Guide"

### ISSUE THREAD

**Issue by d89** [h-da/geli#415]
- [x] Every primary action button should be blue (just like the save-button looks like at the moment)
- [x] Remove the purple buttons
- [x] Every action that destroys / deletes something should be red
- [x] GELI Design Guide is in Wiki (e.g. in Frontend section of Best Practices)

**Comment by micpah** [comment]
Added checkbox for Wiki entry

**Comment by micpah** [comment]
@d89: What about the floating button? Should it remain pink? 
![image](https://user-images.githubusercontent.com/9725083/33900798-0313b848-df70-11e7-9392-d84247693eaf.png)

**Comment by d89** [comment]
Let's leave the floating action button as it is for now :). Love the new consistent buttons everywhere 👍
