### ISSUE TITLE
Update backend service to use non deprecated functions

### ISSUE THREAD

**Issue by grosspersky** [h-da/geli#417]
# User Story

### As a: 
developer

### I want:
no deprecated code

### so that:
my application stays up to date and doesn't break completely on further updates

## Acceptance criteria:
- [ ] Backend service doesn't use deprecated angular functionalities.

## Additional info:

Imports from ``@angular/http`` are deprecated.

**Comment by d89** [comment]
Technical story - no review necessary, pushing this over :).
