### ISSUE TITLE
Refactor unit and progress

### ISSUE THREAD

**Issue by grosspersky** [h-da/geli#425]
# User Story

### As a: 
developer

### I want:
a nice clean way for handling units and progress

### so that:
new unit and progress types can be added more easily

## Acceptance criteria:
- [x] unified controller for units
- [x] unified controller for progress
- [x] migration script for old database schema 

## Additional info:
#269  will be solved together with this

------
_Please tag this issue if you are sure to which tag(s) it belongs._

**Comment by d89** [comment]
Technical story - moving it over.
