### ISSUE TITLE
Introduce routing to course management

### ISSUE THREAD

**Issue by grosspersky** [h-da/geli#428]
# User Story

### As a: 
teacher

### I want:
direct links to edit specific lectures and units

### so that:
i can keep deep links to edit specific data faster

## Acceptance criteria:
- [x] pressing the edit button for units closes them if they are open
- [x] use a unique route for each tab currently available
- [x] general tab uses the current route
- [x] direct routes to all relevant paths are available
  - [x] route for editing a specific lecture
  - [x] route for adding a lecture
  - [x] route for editing a specific unit
  - [x] route for adding a unit of an available type

## Additional info:

------
_Please tag this issue if you are sure to which tag(s) it belongs._

**Comment by felixbrucker** [comment]
Todo:
- [ ] remove unneeded functions/code left from refactoring
- [ ] unify duplicate functions
- [ ] styling

**Comment by d89** [comment]
Yep, looks good 👍
