### ISSUE TITLE
HTTPS 

### ISSUE THREAD

**Issue by Bouabidi** [h-da/geli#431]
# User Story
Iam working on a webrtc project using Geli-Plattform and i would like to use https protocol.
I get always a proxy problem:

"Error occured while trying to proxy to: localhost:4200/api/auth/login"

### I want:

how can i change my proxy.config.json file

Thank you.

**Comment by aeimer** [comment]
When exactly does this error occur?

**Comment by aeimer** [comment]
Furthermore, why do you want to use SSL encryption in Dev?

**Comment by felixbrucker** [comment]
I suggest using a nginx reverse proxy in front of everything which does the SSL/TLS termination.

**Comment by lukaskorte** [comment]
This is not an issue with geli. The way to go is to use the suggestion by @felixbrucker.
