### ISSUE TITLE
Introduce API-Docu, build automatically

### ISSUE THREAD

**Issue by aeimer** [h-da/geli#441]
# User Story

### As a: 
Developer

### I want:
to have an API-Documentation

### so that:
I can see all URL-Paths and their functions.

## Acceptance criteria:
- [x] All API-Functions are commented
- [x] Build the Documentation on build time
- [x] The documentation should be generated only on tagged builds
- [x] Publish the build (as GH Pages)
- [x] The version of the docu should be switched

## Additional info:
https://pages.github.com/

------
_Please tag this issue if you are sure to which tag(s) it belongs._

**Comment by micpah** [comment]
- https://swagger.io/
- https://stackoverflow.com/questions/31300756/can-swagger-autogenerate-its-yaml-based-on-existing-express-routes
- https://github.com/RSuter/NSwag
