### ISSUE TITLE
Add dark theme

### ISSUE THREAD

**Issue by aeimer** [h-da/geli#447]
# User Story

### As a: 
User

### I want:
to choose between the current light them and a dark theme

### so that:
my eyes don't hurt that much after using the platform (at night)

## Acceptance criteria:
- [ ] let the user choose which theme he wants
- [ ] design a dark theme

## Additional info:
- we could make the change time depending, so eg after 10 o'clock pm till 6 o'clock the dark theme applies automatically if wanted

------
_Please tag this issue if you are sure to which tag(s) it belongs._

**Comment by d89** [comment]
Looks fine! Still reopening this, because I can't find the required documentation yet which we talked about in the course. I would suggest putting it here: https://github.com/h-da/geli/wiki/Style-Guide

**Comment by d89** [comment]
Ah, and please go through every unit once. I just discovered this when adding a task:

![image](https://user-images.githubusercontent.com/423154/35198326-77294710-feed-11e7-87a4-fc4b91370b6e.png)

**Comment by d89** [comment]
Looks good now 👍
