### ISSUE TITLE
Collapsing / Expanding a unit is broken

### ISSUE THREAD

**Issue by d89** [h-da/geli#451]
Here is what happens when I click the expand / collapse button:

![capture](https://user-images.githubusercontent.com/423154/34433480-f69c6476-ec7f-11e7-85b9-c498d9fdd93f.PNG)

**Comment by d89** [comment]
Probably related: Same happens when I click on a multiple choice answer:

![capture3](https://user-images.githubusercontent.com/423154/34433860-662c1af0-ec82-11e7-84e6-f1d1decfb18d.PNG)

**Comment by aeimer** [comment]
I have refactored the expandableDiv. Maybe I have made something wrong...

**Comment by d89** [comment]
Sorry, this still happens to me even after a hard refresh with opened Dev tools.

![image](https://user-images.githubusercontent.com/423154/34461408-3a383b06-ee29-11e7-8dbe-7cf6074cd067.png)

Expanding / collapsing works now and answering multi choice questions aswell - but the error log doesn't look very friendly. I am logged in as administrator in this course: https://staging.geli.fbi.h-da.de/course/597df6d5b7a9c0000616637f

**Comment by aeimer** [comment]
I can recreate the problem, on FF I get the following log on the "geography lesson":
![grafik](https://user-images.githubusercontent.com/25035182/34462923-1446d22a-ee4e-11e7-9da3-1b51fe2d67e7.png)
On the "some nice questions" task-unit the problem does not get thrown... After the Error got thrown once, the problemless questions cant be reseted, I get the same error as above.

I created a new course with a lecture which has two task units, there is no error!
https://staging.geli.fbi.h-da.de/course/5a490fd7b2e11700067da1e9

**Comment by d89** [comment]
Still happens to me, in an ordinary Chrome on the course https://staging.geli.fbi.h-da.de/course/597df6d5b7a9c0000616637f (and somehow only here).

![test](https://user-images.githubusercontent.com/423154/35198216-df966cb2-feeb-11e7-8660-33615ae36353.gif)

**Comment by aeimer** [comment]
Looks like it's caused by inconsistent data?!

**Comment by lukaskorte** [comment]
This is because of a corrupt Task, will remove the Task and test again
![image](https://user-images.githubusercontent.com/3072741/35240926-35c6601e-ffb5-11e7-9591-080f6b1645a6.png)

**Comment by d89** [comment]
Nice 👍
