### ISSUE TITLE
UI gibberish for tasks

### ISSUE THREAD

**Issue by d89** [h-da/geli#453]
Not sure what happened here. This can be seen in the course "Fortgeschrittene Webentwicklung" on the staging system when logged in as student: https://staging.geli.fbi.h-da.de/course/597df6d5b7a9c0000616637f

![capture2](https://user-images.githubusercontent.com/423154/34433815-0e5f4ed2-ec82-11e7-9bde-e617473287a7.PNG)

**Comment by aeimer** [comment]
Looks like a false `mat-icon` tag...

**Comment by lukaskorte** [comment]
I could not reproduce this one. The icon is "check" and should work: https://material.io/icons/#ic_check

Maybe also caused by #451 .

**Comment by lukaskorte** [comment]
In case you can still reproduce this during the next review, your browser, OS and their versions would be helpful :)

**Comment by aeimer** [comment]
This often happens when the browser could not load the icon font...

**Comment by d89** [comment]
Can't reproduce this aswell any longer. Moving it to "successfully reviewed" 👍
