### ISSUE TITLE
Bug: Can't edit any units

### ISSUE THREAD

**Issue by PatrickSkowronek** [h-da/geli#469]
# User Story

### As a: 
Teacher or Admin

### I want:
To edit any unit type after creating.

## Acceptance criteria:
- [ ] make unit editable aging

## Additional info:
I made a gif
![peek 2018-01-14 13-51](https://user-images.githubusercontent.com/32745673/34916097-69f1364a-f932-11e7-9d16-e28466087d7a.gif)

------
_Please tag this issue if you are sure to which tag(s) it belongs._

**Comment by felixbrucker** [comment]
Is getting fixed with my PR: https://github.com/h-da/geli/pull/468

specifically: https://github.com/h-da/geli/pull/468/commits/97a3abf746f6742427080be9e78939e02ac90085
