### ISSUE TITLE
add picture to user

### ISSUE THREAD

**Issue by utetrapp** [h-da/geli#47]
# User Story

### As a: 
course member (student or teacher)

### I want:
see a picture within each student list etc.

### so that:
remember the students more easily.

## Acceptance criteria:
- [x] The user profile contains an optinal picture (upload and taking a picture with the builtin camera).
- [x] Within each list of students, first name, last name and picture is visible.

**Comment by khase** [comment]
Can the first checkpoint be cheched since we use gravatar or should the user be able to upload/take a explicid picture?

**Comment by utetrapp** [comment]
I think it is better, if the user can change the picture. However, it is not an important issue. It's up to you ;-)
