### ISSUE TITLE
deadlines within questions and assignments

### ISSUE THREAD

**Issue by utetrapp** [h-da/geli#50]
# User Story

### As a: 
teacher

### I want:
set a deadline for a given assignment/question

### so that:
able to address the problems in the lecture.

## Storypoints:
?

## Acceptance criteria:
- [x] Possiblity to set a deadline (optional!). After this deadline the students may not upload their answers or work on the questions.

**Comment by felixbrucker** [comment]
https://github.com/angular/material2/issues/5648

**Comment by felixbrucker** [comment]
As soon as `@angular/material-moment-adapter` hits npm we should use it.

See https://github.com/angular/material2/issues/7464

**Comment by d89** [comment]
looks good 👍
