### ISSUE TITLE
🐛 BUG: Can not  call error.json() method by all errors.

### ISSUE THREAD

**Issue by OliverNeff** [h-da/geli#513]
# User Story

### As a: 
User

### I want:
see meaningful error messages.

### so that:
I know where is an error.

## Acceptance criteria:
- [ ] There is not an error when an exception is thrown.
- [ ] Error messages are shown well. 
- [ ] Duration of snackbar is long enough that you can read the message.
- [ ] You can click on dismiss by all error messages.

## Additional info:

------
_Please tag this issue if you are sure to which tag(s) it belongs._

**Comment by PatrickSkowronek** [comment]
The behavior of httperror from angular changed with angular5. This should be done with #572 !
