### ISSUE TITLE
Put input fields into forms

### ISSUE THREAD

**Issue by aeimer** [h-da/geli#532]
# User Story

### As a: 
User

### I want:
to (almost) all input fields/buttons encapsulated into a form tag

### so that:
I can hit "enter" to send the form

**Comment by Gargamil** [comment]
Currently the file upload is broken. It is handled with PickMediaDialog. But by opening this, the user has no possibility for uploading files.. 
This must be fixed.

So, what do you think about of using UploadFormDialog? (Or something similar?)

Sorry. As i understand now, it is not broken, its the way it works. This is very very confusing. 

As i see, this is exactly #728.

**Comment by Gargamil** [comment]
Todo:
- [ ] Tutorial for creating new unit types in in `unit-form-component`
- [ ] Remove useless eventemitter submitDone
- [ ] Migrate to new Snackbar-Service
- [ ] Comments
- [ ] pass linter
- [ ] refactor other forms: `whitelist-edit` & `upload-form-component`
- [ ] PR

**Comment by mleppla** [comment]
"Cancel" is not working anymore..  Instead of Cancel, there is a submit?!

**Comment by Gargamil** [comment]
@maxleppla sorry, but can you be more precisely? Can't reproduce this bug.... :(
Is it correct, that you mean the 'Cancel' Button under the units? 
Does the bug appear, when you create an new unit? or/and by canceling in edit mode? 
Is the button type: `type="reset"`?
Screenshots or some short video etc. are welcome 👍
