### ISSUE TITLE
🐛 BUG: Video Unit can grow too big

### ISSUE THREAD

**Issue by aeimer** [h-da/geli#534]
The video gets to big:

![grafik](https://user-images.githubusercontent.com/25035182/37857919-67147f56-2eff-11e8-9867-1dd16c2bbcaf.png)

**Comment by dboschm** [comment]
I guess, the size of videoplayers is currently determined by the video resolution. In some cases (also in the following screenshot) this makes the UI look inconsistent. There should be the same size for all videoplayers shown at the same time.

![image](https://user-images.githubusercontent.com/33879057/38519590-9f3c270a-3c40-11e8-91ff-2f99a6f0aefc.png)

**Comment by aeimer** [comment]
@dboschm It shouldn't be a fixed size! You should set a max-width...

**Comment by dboschm** [comment]
@aeimer I'm fine with a variable size, because of the resposivness of the application. But a max-width is not enough to get a nice UI (as my screeshot shows). There should also be something like a width-synchronization between multiple video players (e.g. width of the smallest one, for all other videoplayers).

**Comment by aeimer** [comment]
@dboschm why should we show videos smaller than they are?

**Comment by Gargamil** [comment]
maybe the youtube approach is a nice implementation of this. I think they start with a smaller size (which can be fixed) and then you can change it to the "movie-mode" (You know what i mean).

**Comment by aeimer** [comment]
Yeah, wie not. It sound like a lot of work, but I would keep it simple... Set a max-size and if you need it bigger you need to go to the fullscreen mode. The max-width does not need to be 100%, on desktop it may be enough to set it to 50 oder 60%. On smaller viewports you should set it to 100%

**Comment by dboschm** [comment]
@aeimer the width of the smallest one was my first Idea to get a consistent width for all videoplayers shown at the same time. We can also take the Resolution of the biggest one and scale the smaller ones up. Important for me is, that two videos next to each other do not have different sizes.

**Comment by Gargamil** [comment]
@dboschm 
> We can also take the Resolution of the biggest one and scale the smaller ones up. 
Think the opposit is better. Better have more resolution in less space than have less resolution in more space (pixels will be visible)

Also: Maybe some upload-restriction for the resolution range would be helpfull. (e.g. smallest: 720p highest: 4k?)

**Comment by aeimer** [comment]
@dboschm In my opionin this makes no sense. I can understand that from an design-point-of-view, but it will make you to write ugly code to find out the sizes and so on... So I disagree with the same size videos. The normal usecase will be 1080p Videos, so they all will grow to the same max-width.

> Maybe some upload-restriction for the resolution range would be helpfull. (e.g. smallest: 720p highest: 4k?)

Bad idea, don't do it for ONLY to "look good"...

This is my point of view, you don't need to do it that way. You now have to power to model this project as you want it ;)

**Comment by Gargamil** [comment]
> Bad idea, don't do it for ONLY to "look good"...

Not only for look good. The reason is: the video has to be useable. smaller than 720p maybe isnt't usefull? Specially think of screenrecords and so on

**Comment by aeimer** [comment]
@Gargamil you don't know what kind of videos teachers want to upload... I wouldn't restict it. My opinion :)
