### ISSUE TITLE
🐛 BUG: Some UI Bugs in Code Kata Unit 

### ISSUE THREAD

**Issue by dboschm** [h-da/geli#543]
- too much space beside code editors (positioning of Deadline Text looks bad)
- Line numbers in the second code viewer count from e.g. 4 (n+1) upwards continuing the line numbers of the first code viewer. But the line numbers of the third code viewer (test) also count from 4 (n+1) instead of summing up the lines of the first and second code editor.
- missing space between validation button and log output
![image](https://user-images.githubusercontent.com/33879057/38394076-61d497d2-392d-11e8-83a8-8af51f2cc8dd.png)

**Comment by PatrickSkowronek** [comment]
Good observation. I would add a better representation of the log, like a snackbar. Text under the button is in opinion not a good solution.

**Comment by dboschm** [comment]
@PatrickSkowronek I also dislike the plain text solution. But I see one small problem using a snackbar for displaying the logs: a snackbar disappears after a few seconds, but logs are possibly too long to be completely read and understood in this short time.

**Comment by d89** [comment]
Like it 👍
