### ISSUE TITLE
🐛 BUG: duplicate code in codekata after saving

### ISSUE THREAD

**Issue by dboschm** [h-da/geli#544]
definition and test code are exported two times
![image](https://user-images.githubusercontent.com/33879057/38395197-0952fbf8-3932-11e8-9dde-ca384bf6bf25.png)

**Comment by danielkesselberg** [comment]
I see this issue when editing a unit. When i add a code kata for the first time it works as expected.

![image](https://user-images.githubusercontent.com/3902676/38439236-30d9c2be-39dd-11e8-8fd9-7eef25094dbe.png)

But when i hit the save button for the code kata a second time the code is duplicated.
![image](https://user-images.githubusercontent.com/3902676/38439297-65189f5a-39dd-11e8-9282-d89d50efbd6e.png)

**Comment by d89** [comment]
Looks good 👍
