### ISSUE TITLE
Change the language icon into the language flag

### ISSUE THREAD

**Issue by mleppla** [h-da/geli#554]
# User Story

### As a: 
student / teacher

### I want:
I like to know, which language I have currently selected

### so that:
So I can see on the first view the selected language

## Acceptance criteria:
- [x] see the country flag of the selected language
- [x] When changing the language, also the selected flag sould be changed

## Additional info:
For the current language the country code is used, not the language flag but still fixed.
------
_Please tag this issue if you are sure to which tag(s) it belongs._

**Comment by wurmc** [comment]
could it also be the country code instead of the flag?!
for example: DE or EN.

**Comment by mleppla** [comment]
also possible
