### ISSUE TITLE
Add the profile Image on the profile page

### ISSUE THREAD

**Issue by mleppla** [h-da/geli#558]
# User Story

### As a: 
student / teacher

### I want:
I like to see my uploaded picture on the profile page

![profile](https://user-images.githubusercontent.com/38111097/38520596-7fd69a3c-3c43-11e8-83a9-b3c4b568535c.PNG)

## Acceptance criteria:
- [ ] See the profile picture on the profile page

## Additional info:

------
_Please tag this issue if you are sure to which tag(s) it belongs._

**Comment by PatrickSkowronek** [comment]
Can you please provide a image with this problem, currently I can't see what do you mean.

**Comment by mleppla** [comment]
have a look at the picture in the issue description. You can upload a picture, but you only see it in the little avator on the right upper side

**Comment by d89** [comment]
Looks good 👍
