### ISSUE TITLE
Add Tooltips to buttons

### ISSUE THREAD

**Issue by mleppla** [h-da/geli#560]
# User Story

### As a: 
student / teacher

### I want:
I like to see on the first view on the button, which function the button has

## Acceptance criteria:
- [x] add a meaningful term to the buttons
- [x] add term to the language resource file
- [x] translated into the different languages

## Additional info:

------
_Please tag this issue if you are sure to which tag(s) it belongs._

**Comment by PatrickSkowronek** [comment]
I hope you mean this https://material.angular.io/components/tooltip/overview . In some cases there already tooltips.

**Comment by mleppla** [comment]
Perhaps there are also tooltips missing. What I mean is that some buttons are maybe better for understanding with labels. I think, we should discuss this and some more GUI aspects togehter in a group. There are also some usability issues which could be better e.g. never add an item named default,... (https://meiert.com/de/publications/translations/asktog.com/firstprinciples/).

**Comment by aeimer** [comment]
Try to keep the design as close as possible to what Angular Material defines.
