### ISSUE TITLE
Resize the video player

### ISSUE THREAD

**Issue by mleppla** [h-da/geli#562]
# User Story

### As a: 
student / teacher

### I want:
I like to see video previews (of the video player) on max. the width of the screen

![size_video](https://user-images.githubusercontent.com/38111097/38420247-65372392-39a3-11e8-9b48-160d4ec9d7e1.png)

## Acceptance criteria:
- [ ] the video should be shown with a size that I can see the full preview image on the screen

## Additional info:

------
_Please tag this issue if you are sure to which tag(s) it belongs._

**Comment by mleppla** [comment]
ok sry, how can I remove this issue

**Comment by armel22** [comment]
The GITHUB API only allows you to open/close/reopen issues

**Comment by armel22** [comment]
you can edit  it to a different issue

**Comment by PatrickSkowronek** [comment]
indeed duplicate to #534 . Closed
