### ISSUE TITLE
add possibility to sort courses instead of last visited 

### ISSUE THREAD

**Issue by wurmc** [h-da/geli#567]
# User Story

### As a: 
user

### I want:
to have the possibility to sort courses on the dashboard, for example alphabetically.

### so that:
I can find courses more easily.

## Acceptance criteria:
- [ ] courses sortable

## Additional info:
Without sorting the overview of my courses is quite complicated if the number of courses is high enough.
------
_Please tag this issue if you are sure to which tag(s) it belongs._

**Comment by PatrickSkowronek** [comment]
At the moment the "my courses" is sorted in order of visit

**Comment by aeimer** [comment]
We've jsut changed it :D #276
