### ISSUE TITLE
🐛 BUG: Trying to re-register fails silently

### ISSUE THREAD

**Issue by torss** [h-da/geli#570]
Trying to register an account using an existing EMail address fails silently, leaving the "Register" button deactivated.
![2018-04-06_160920processed](https://user-images.githubusercontent.com/37229901/38426389-d2f2c8ba-39b6-11e8-8c6b-63525467bf59.png)

Tested "Register as Student" on the staging and live system using Firefox 59 and Chrome 65.
Chrome console error message:
![2018-04-06_161554](https://user-images.githubusercontent.com/37229901/38426425-e88168b2-39b6-11e8-8f3d-08333f276bc1.png)

**Comment by PatrickSkowronek** [comment]
This issue is related to https://github.com/h-da/geli/issues/572
