### ISSUE TITLE
🐛 BUG: Frontend uses wrong error message

### ISSUE THREAD

**Issue by PatrickSkowronek** [h-da/geli#572]
# User Story

### As a: 

User

### I want:

The correct Error message!

At the moment there are two components where the old error will be printed, which is not defined any more.
-> https://github.com/h-da/geli/blob/9084ceab25e751729311066835f3a633b177751c/app/webFrontend/src/app/unit/code-kata-unit/code-kata-unit.component.ts#L83
-> https://github.com/h-da/geli/blob/9084ceab25e751729311066835f3a633b177751c/app/webFrontend/src/app/auth/register/register.component.ts#L80

There are properly even more, which are didn't crash yet.

## Acceptance criteria:
- [x] Fix the two components(code-kata & register)
- [ ] Search for more occurrences and fix them

## Additional info:

A occurrence was fixed in https://github.com/h-da/geli/issues/520
Sentry Issue ID: STAGING-4P
------
_Please tag this issue if you are sure to which tag(s) it belongs._

**Comment by danielkesselberg** [comment]
I added a first pull request for a few occurences. But there are still enough left for @wurmc. I would like to ask @PatrickSkowronek & @HPunktOchs about: https://github.com/h-da/geli/blob/497c95f1cd60602a5718cad6b0d65f3324fa06c1/app/webFrontend/src/app/course/course-edit/general-tab/general-tab.component.ts#L145-L146

It looks like there are two kind of errors. First one is the (now broken) call for BadRequestError.  **Second one is for?**

The logic is not for mongoos. When you add a maxlength for name to api/src/models/Course.ts and try to create a new course with name "12345" you run into a ValidationError (and there is no errmsg property).

**Comment by danielkesselberg** [comment]
@wurmc 
https://github.com/h-da/geli/blob/497c95f1cd60602a5718cad6b0d65f3324fa06c1/app/webFrontend/src/app/unit/unit-form/code-kata-unit-form/code-kata-unit-form.component.ts#L120
https://github.com/h-da/geli/blob/497c95f1cd60602a5718cad6b0d65f3324fa06c1/app/webFrontend/src/app/unit/unit-form/code-kata-unit-form/code-kata-unit-form.component.ts#L139
https://github.com/h-da/geli/blob/e9f4f133f40cd65d97155d2ede578ce1467b724d/app/webFrontend/src/app/user/user-edit/user-edit.component.ts#L74
https://github.com/h-da/geli/blob/e9f4f133f40cd65d97155d2ede578ce1467b724d/app/webFrontend/src/app/user/user-edit/user-edit.component.ts#L153
https://github.com/h-da/geli/blob/497c95f1cd60602a5718cad6b0d65f3324fa06c1/app/webFrontend/src/app/course/course-edit/course-manage-content/lecture-edit/lecture-edit.component.ts#L88
https://github.com/h-da/geli/blob/497c95f1cd60602a5718cad6b0d65f3324fa06c1/app/webFrontend/src/app/course/course-edit/course-manage-content/lecture-edit/lecture-edit.component.ts#L218
https://github.com/h-da/geli/blob/3404ab3d53dd220ef2519f59f3c9e313715c68d1/app/webFrontend/src/app/course/course-new/course-new.component.ts#L44

**Comment by PatrickSkowronek** [comment]
@danielkesselberg at the moment there is no error code in this function https://github.com/h-da/geli/blob/280a27ea721bf0dd6f3cde66b33cb3b0e277dee1/api/src/controllers/CourseController.ts#L595 . You need to add the error handling here as well. If findOne fails it send the validation error automatically.

**Comment by d89** [comment]
Did not find any occurrence of an invalid error message yet 👍
