### ISSUE TITLE
Profile layout space usage optimization

### ISSUE THREAD

**Issue by torss** [h-da/geli#573]
# User Story

### As a:

user

### I want:

that the profile view screen space usage is optimized

### so that:

the ergonomics / aesthetics are (slightly) improved when using a larger (e.g. desktop) display.

## Acceptance criteria:

* [ ] The profile view has an improved layout to reduce wasted space on larger displays.

## Additional info:

(See comments.)

# Original issue: Center "Profile" and "Edit profile"

### As a:

user

### I want:

that the "Profile" and "Edit profile" views are centered

### so that:

the ergonomics / aesthetics are (slightly) improved when using a larger (e.g. desktop) display.

## Acceptance criteria:

* [ ] "Profile" view (user-profile component) is centered.
* [ ] "Edit profile" view (user-edit component) is centered.

## Additional info:

It currently looks like this (i.e. left aligned):

![2018-04-06_163046processed](https://user-images.githubusercontent.com/37229901/38427912-cf8973aa-39ba-11e8-842b-c21735324d2a.png)

![2018-04-06_163020processed](https://user-images.githubusercontent.com/37229901/38427917-d2d2f496-39ba-11e8-88f5-769897579edb.png)

**Comment by grosspersky** [comment]
You should take note that there can be additional data on the profile page, which will show your course progress if you are part of a course with progressable units. If you center the profile page it would look a bit strange.
![grafik](https://user-images.githubusercontent.com/11839276/38436385-c7d079f0-39d4-11e8-8f49-9c88f2e140c4.png)

**Comment by torss** [comment]
Ah, I see. What do you think about these:
Mock-up 0:
![38436385-c7d079f0-39d4-11e8-8f49-9c88f2e140c4mockup0](https://user-images.githubusercontent.com/37229901/38437708-a59c7588-39d8-11e8-9dad-c50fb80384d2.png)
Mock-up 1:
![38436385-c7d079f0-39d4-11e8-8f49-9c88f2e140c4mockup1](https://user-images.githubusercontent.com/37229901/38437719-acf47772-39d8-11e8-8c9b-d3e85b75ca69.png)
Mock-up 2:
![38436385-c7d079f0-39d4-11e8-8f49-9c88f2e140c4mockup2](https://user-images.githubusercontent.com/37229901/38437723-afd1a5b4-39d8-11e8-9700-708c00f97ff2.png)

I would like something akin to Mock-up 1, but - besides this being subjective - would that clash with the style guide? (I have not yet read the Material Design style guide.)

**Comment by grosspersky** [comment]
If I remember correctly you should never completly center some content like you did in Mock-up 1.
Maybe something like this could further improve the reduction of the existing white space:
![grafik](https://user-images.githubusercontent.com/11839276/38441733-0a33aa54-39e6-11e8-92be-67cb14807a98.png)

To prevent this waist of space even more you could also add additional informations to the course card like upcoming deadlines for the assignments in each course or something else that is connected specially to this user and could be displayed on this page.

**Comment by PatrickSkowronek** [comment]
@grosspersky good mock-up, I like it!

**Comment by aeimer** [comment]
But keep in to develop your pages MOBILE FIRST ;)

**Comment by d89** [comment]
Like it 👍
