### ISSUE TITLE
Add const times for snackbars

### ISSUE THREAD

**Issue by PatrickSkowronek** [h-da/geli#574]
# User Story

All snackbars in the frontend have different duration time. It should exists a general constant for short, medium and long times. An all snackbars should have a dismiss button!  

## Acceptance criteria:
- [ ] Add short, medium and long constant values
- [ ] change all snackbars to the constant values
- [ ] Add dismiss buttons to all snackbars

**Comment by aeimer** [comment]
You could add a "SnackbarHelper" which you only need to pass the text

**Comment by PatrickSkowronek** [comment]
@aeimer good hint

**Comment by danielkesselberg** [comment]
@PatrickSkowronek could you take a first look at #657 and tell me if we are heading into the right direction before i migrate from matSnackBar to snackBarService? Thank you in advance!

**Comment by PatrickSkowronek** [comment]
@danielkesselberg I will look into it, as pointed out in #657 . In travis it is working, and we want to add frontend testcases this semester.

**Comment by danielkesselberg** [comment]
Please ignore the test related stuff. I would like to hear your thoughts about the SnackBarService.  Thank you!

**Comment by PatrickSkowronek** [comment]
@danielkesselberg I like the new Service, except the short duration should be 3 sec at least. Some messages are longer.

**Comment by danielkesselberg** [comment]
I set 3000 for short, 6000 as default and 9000 for long. Ok?

**Comment by PatrickSkowronek** [comment]
I would prefer it, lets test it. If we want to change it, there is only one place to change the code!
