### ISSUE TITLE
GitHub label documentation

### ISSUE THREAD

**Issue by torss** [h-da/geli#577]
# User Story

### As a: 

new contributor without experience

### I want:

to quickly understand what exactly each label is supposed to mean

### so that:

there is no ambiguity in their usage.

## Acceptance criteria:

- [ ] Decide whether or not the more obvious or GitHub-official labels should be mentioned in further documentation. E.g. these may be considered sufficiently self-describing / well known:
    - `bug`
    - `duplicate`
    - `good first issue`
    - `help wanted`
    - `invalid`
    - `nice to have`
    - `question`
    - `refactoring`
    - `trivial`
    - `wontfix`
- [ ] All labels deemed even slightly unclear are clarified in a Markdown document, e.g. these:
    - [ ] `api` (what exactly?)
    - [ ] `blocked` (which context?)
    - [ ] `enhancement` (difference to regular feature?)
    - [ ] `infrastructure` (what exactly?)
    - [ ] `v1.0` (what exactly?)
    - [ ] `web-frontend` (what exactly?)
- [ ] The file is mentioned in / The documentation is part of the contributing guide.
- [ ] Every label should preferably have a small (tooltip) description [here](labels).
 
## Additional info:

Related to #136.

**Comment by PatrickSkowronek** [comment]
@torss I added descriptions on the labels. Is there any missing or not describing label?

**Comment by torss** [comment]
We determined that no further label documentation is desired in the meeting today.
