### ISSUE TITLE
Add visible flag to unit / Make available on

### ISSUE THREAD

**Issue by danielkesselberg** [h-da/geli#582]
User Story

### As a: 

Teacher

### I want:

to decide for every unit in a course if these is visible or not. A possible use case could be: setup the course at the beginning of the semester but hide the content. 

### so that:

Unit is visible when checkbox is on. By default the checkbox should be checked. When "unit is not visible" checked than there should be another option "make available on" with a datepicker.  When current date is greater/equal to date input the visible flag should be changed to visible.

## Acceptance criteria:
- [x] Checkbox or Toggle: Unit visible / Unit not visible
- [ ] Datepicker whe Unit not visible
- [ ] Unit is visible when current date > input date

## Additional info:

This issue is blocked by #556

**Comment by khase** [comment]
There is an option implemented "isActive" which basically gives the Teacher the possibility to hide this course for everyone but him.

![image](https://user-images.githubusercontent.com/26968077/38606260-d7302a2c-3d75-11e8-94a2-bccc7a38984c.png)

**Comment by danielkesselberg** [comment]
Thanks @khase for pointing this out. Let me clarify this issue. I would like the hide Units/Items inside a course. Imagine you setup the course once and duplicate it each semester. But summer is shorter than winter and you want to hide one Unit. Right now you have to delete it. Just to add one use case for this.

**Comment by PatrickSkowronek** [comment]
@khase he want's to set single lectures or unit to visible or not.

**Comment by PatrickSkowronek** [comment]
@danielkesselberg why is it blocked?
