### ISSUE TITLE
Add a max. length to firstname and lastname

### ISSUE THREAD

**Issue by ChrisEnpunkt** [h-da/geli#585]
# User Story

### As a: 
Student

### I should not able to:
change my firstname and lastname without character limit

![lol](https://user-images.githubusercontent.com/27723642/38443293-873db4f4-39eb-11e8-8e2a-1b0f5d69f0b2.png)

## Acceptance criteria:
- [ ] Can't change firstname or lastname without a limit

------

**Comment by torss** [comment]
A limited is needed for the matriculation number as well.
