### ISSUE TITLE
🐛 BUG: add top/bottom spacing between buttons for mobile view in course edit

### ISSUE THREAD

**Issue by fwitulski** [h-da/geli#590]
bottom/top spacing missing between buttons on mobile view at course edit

![grafik](https://user-images.githubusercontent.com/32933845/38446514-cb3a7194-39f8-11e8-813e-c607a227cb90.png)

example <= 406px width

Same for login page!

## Acceptance criteria:
- [ ] visible bottom/top spacing between buttons on mobile view at course edit
- [ ] visible bottom/top spacing between buttons on mobile view at login

------
_Please tag this issue if you are sure to which tag(s) it belongs._

**Comment by d89** [comment]
Looks fine on mobile now 👍
