### ISSUE TITLE
🐛 BUG: course progress display partly out of bound on mobile

### ISSUE THREAD

**Issue by fwitulski** [h-da/geli#593]
course progress display is partly out of bound for device width below about 540px

![grafik](https://user-images.githubusercontent.com/32933845/38447706-661febf2-39ff-11e8-9cf0-0bc8cd55d5b2.png)

------
_Please tag this issue if you are sure to which tag(s) it belongs._

**Comment by d89** [comment]
Awesome mobile appearance 👍
