### ISSUE TITLE
Resend Activation Email

### ISSUE THREAD

**Issue by Gargamil** [h-da/geli#601]
# User Story

### As a: 

Student/Teacher

### I want:

to resend my Activation Email, if i don't received it after a few minutes. Maybe with combination of changing my mail-address (typo) before resending.

### so that:

I receive my activation Link

## Acceptance criteria:
- [ ] Resend (or requesting new) activation email when having a not activated account
- [ ] Change my mail-address before request the mail (for fixing typo)

## Additional info:

------
_Please tag this issue if you are sure to which tag(s) it belongs._

**Comment by fwitulski** [comment]
Will remove firstname from feature in https://github.com/h-da/geli/issues/711
