### ISSUE TITLE
Add some board / discussion in course

### ISSUE THREAD

**Issue by Gargamil** [h-da/geli#602]
# User Story

### As a: 

Student / Teacher

### I want:

have a (simple and optional) discussion board, where i can ask and discuss with other students or the teacher(s)

### so that:
i can ask questions and answer

## Acceptance criteria:
- [ ] simple discussion board
- [ ] optionally enabled by teacher

------
_Please tag this issue if you are sure to which tag(s) it belongs._

**Comment by aeimer** [comment]
duplicate of #46 ?!

**Comment by Gargamil** [comment]
Seems so..

**Comment by PatrickSkowronek** [comment]
Indeed it is! Closed!
