### ISSUE TITLE
Format-Check for Image-Upload (profile page)

### ISSUE THREAD

**Issue by mleppla** [h-da/geli#605]
# User Story

### As a: 
student / teacher

### I want:
I want to upload pictures only on the profile-page

## Acceptance criteria:
- [ ] Upload with some image formats possible (e.g. jpg, png)
- [ ] Not able to upload exe-files, pdfs,...

## Additional info:
Now, I can upload exe-files and so on...
------
_Please tag this issue if you are sure to which tag(s) it belongs._

**Comment by Gargamil** [comment]
the api should check the correct mime types.  (A list of "correct" types could be: `image/gif, image/png, image/jpeg, image/bmp, image/svg+xml`)

**Comment by Gargamil** [comment]
Related to #581

**Comment by PatrickSkowronek** [comment]
Same as #581 closed
