### ISSUE TITLE
Add Grid CSS System

### ISSUE THREAD

**Issue by Gargamil** [h-da/geli#613]
# User Story

### As a: 

Developer

### I want:

to use a css grid system for better & general layouting and better mobile optimization. For example the approach of Bootstrap (only grid) or [Uikit](https://getuikit.com/) is a good starting point. 

## Acceptance criteria:
- [ ] have a stable and feature-rich css grid system

## Additional info:

------
_Please tag this issue if you are sure to which tag(s) it belongs._

**Comment by ChrisEnpunkt** [comment]
May be this package?
https://www.npmjs.com/package/bootstrap-4-grid
It only contains the bootstrap 4 grid system and some layout utilities.
