### ISSUE TITLE
Configuration for ng test broken

### ISSUE THREAD

**Issue by danielkesselberg** [h-da/geli#655]
# User Story

## Acceptance criteria:
- [x] Provide working configuration for ng test

## Additional info:

![image](https://user-images.githubusercontent.com/3902676/39050620-62b7d2de-44a6-11e8-8acf-255b0090acb6.png)

**Comment by PatrickSkowronek** [comment]
Currently there are only a few frontend tests. In travis they work. We should add a Issue for some fundamental frontend test.

**Comment by danielkesselberg** [comment]
This issue is about npm run tests and not npm run e2e (see https://github.com/h-da/geli/blob/develop/.travis.yml#L77). When referenced pull request is merged its possible to run npm run tests on localhost.

**Comment by grosspersky** [comment]
This has multiple related issues (and some of them are really old):
* #127 
* #94 
* #14 
This issue seems like a exact duplicate of the incomplete #127.
