### ISSUE TITLE
Automatic negative progress on course enrollment

### ISSUE THREAD

**Issue by PatrickSkowronek** [h-da/geli#715]
# User Story

### I get: a progress on a course, that I just enrolled to. Without even trying!

After enrollment:
![612](https://user-images.githubusercontent.com/32745673/39621036-8b791ce0-4f8d-11e8-8430-243bb44d2a78.png)

**Comment by fwitulski** [comment]
I think this is fine. It tells you that there are 4 tasks to do and you have not done any of them (which is correct since you just enrolled into the course).
Or which behaviour would you like to see?

**Comment by PatrickSkowronek** [comment]
@fwitulski you are right, but nothing is not a good text in my opinion. We should change that!

**Comment by grosspersky** [comment]
@PatrickSkowronek _nothing_ is just a placeholder along with _tried_ and _done_, which should also be reworked. You should investigate if you find a proper translation or description for this.

**Comment by fwitulski** [comment]
@PatrickSkowronek @grosspersky what do you guys think about _open_, _tried_ / _attempted_ and _solved_ ?

**Comment by PatrickSkowronek** [comment]
@fwitulski I would use "not tried", "tried" and "solved"

**Comment by fwitulski** [comment]
sounds fine for me
