### ISSUE TITLE
Frontend styling collecting ticket

### ISSUE THREAD

**Issue by aeimer** [h-da/geli#75]
# User Story

### As a: 
User

### I want:
a good styled website

### so that:
I like the patform even more

## Acceptance criteria:
- [x] add css-transitions for hover/active events
- [ ] add some Kind of Filter  to the Index Image, so the Text is easier to read

## Additional info:
We should collect some todos and then implement them...

**Comment by d89** [comment]
#85

**Comment by aeimer** [comment]
No clue what to do with the index image overlay. NOTHING looks good...

**Comment by aeimer** [comment]
Not necessary
