### ISSUE TITLE
Remove user name (and only use mail address for login)

### ISSUE THREAD

**Issue by d89** [h-da/geli#79]
**To be discussed:** Does the user name add any substantial value? 

**Suggestion:** Use the mail address for logging in. Inside the application, we address the user with Firstname and Last name (which we have anyway)

- [x] Remove username from register form
- [x] Remove username from update/profile form
- [x] Remove username from database shema/model
- [x] Remove username from fixtures???

**Comment by d89** [comment]
I would be fine with using the matrikel number instead of a user name (#48)

**Comment by grosspersky** [comment]
For now we keep the username since they can be used for #46.
