### ISSUE TITLE
Improve User feedback in case of invalid inputs

### ISSUE THREAD

**Issue by d89** [h-da/geli#80]
Some areas of the application (for example login and registration) do not give direct user feedback in case of errors.

**Example:** If I try to login with a student account that is not activated yet, I do not see a helpful error message telling me the cause of the error. 

**Desired behavior:** I want to receive a toast message telling me what went wrong.

**Comment by saitho** [comment]
Another example includes accessing the course without being enrolled.

**Comment by felixbrucker** [comment]
Already done for registration, only login errors missing
