### ISSUE TITLE
Improve readme with a full installation guide

### ISSUE THREAD

**Issue by d89** [h-da/geli#81]
The readme file should contain a full guide on how to setup the application from zero using every available installation method (**vagrant / docker / host system**).

This guide should also contain instructions on how I create user accounts (using `npm run load:fixtures`) and how I activate them so I am actually able to login. 

Please include a guide on how to **setup the mail transfer** aswell.

**Comment by aeimer** [comment]
See #56

**Comment by khase** [comment]
@lukaskorte can this be closed?
