### ISSUE TITLE
Student detail page

### ISSUE THREAD

**Issue by d89** [h-da/geli#86]
# User Story

### As: 

Every user

### I want to:

Have a specific profile page for every user

### so that:

I can see all the publicly available information for every user on a seperate page (name, last name, ...).

## Acceptance criteria:

- [x] Only logged in users are able to access the users profile pages.
- [x] The profile page should be linked from every occurrence of the persons name inside the whole application.
- [x] Teachers and Students should be treated accordingly.

**Comment by khase** [comment]
related #47

**Comment by grosspersky** [comment]
Should we also expose the profile of teachers to the student for contact information?
The issue talks at the beginning and in the end only of student pages. But inbetween all users are mentioned.

**Comment by d89** [comment]
You are right - Every user should have a profile picture, no need for a student <-> teacher distinction here. I updated the issue accordingly.

**Comment by d89** [comment]
When I go to "Course Members" in my own course, I see this:

![image](https://user-images.githubusercontent.com/423154/32290905-d0b9dc0a-bf3b-11e7-9a0c-61d41c2e5a4a.png)

Would be great if we good horizontally center the 3 buttons and display the gravatar there. Then, once I click "details" I end up on the detail page as expected:

![image](https://user-images.githubusercontent.com/423154/32290956-ef9f021c-bf3b-11e7-8c24-06d4037a3290.png)

But why can I click "Edit Profile" and end up on the editing page of my own profile? In my opinion, the "edit profile" button should only be there if I view my own profile.

![image](https://user-images.githubusercontent.com/423154/32290980-0712e63e-bf3c-11e7-9439-9cffb2970ca7.png)

**Comment by d89** [comment]
(feel free to delete the pictures to restore the privacy of your mail addresses) :).

**Comment by grosspersky** [comment]
The first one is a known bug occured during merging, will be solved with #293. Should be solved soon.
Last time I saw this the gravatar or the user image was visible.

The other problem will be investigated here.

**Comment by grosspersky** [comment]
First step investigation: Only the admin user can see the edit profile button on other profiles.
The route is also matching the user that was viewed before.

However on the page itself the wrong dataset is loaded.

**Comment by d89** [comment]
Just retested - when I click "Edit Profile" now

![image](https://user-images.githubusercontent.com/423154/32387066-989a5816-c0c3-11e7-9825-b2010db96e65.png)

... I end up on the "Edit course" view with a crazy url:

![image](https://user-images.githubusercontent.com/423154/32387101-ad740a48-c0c3-11e7-9180-cb8262064e6a.png)

**Comment by grosspersky** [comment]
It seems the following function is missing a slash:
https://github.com/h-da/geli/blob/develop/app/webFrontend/src/app/user/user-details/user-details.component.ts#L34

**Comment by d89** [comment]
Thanks for the hotfix 👍 !
