### ISSUE TITLE
Answer multiple choice questions

### ISSUE THREAD

**Issue by thomassss** [h-da/geli#9]
# User Story

### als: 
Student
### möchte ich:
Fragen vom Teacher beantworten können
### damit ich:
einen Test / ein Testat bestehen kann
### Akzeptanzkriterien:
- [x] Eingaben werden gespeichert
- [ ] Fortschritt wird entsprechend wie in #99 dem Student und Dozent angezeigt

**Comment by aeimer** [comment]
done

**Comment by d89** [comment]
Reopening this, because we don't have the multiple choice questions in the frontend yet.
