### ISSUE TITLE
Free text unit with markdown support

### ISSUE THREAD

**Issue by d89** [h-da/geli#95]
# User Story

### As a: 

teacher

### I want to

... add free text units (in a text area) with markdown support

### so that

I can conveniently add and edit free text content of my sections.

## Acceptance criteria:

- [x] I can choose "free text" when adding a new unit in the section configuration 
- [x] A text area is presented that gives me markdown support
- [x] The markdown input is displayed in proper HTML format on the students frontend

## Additional info:

Live preview would be nice but is be no means required.

**Comment by aeimer** [comment]
I searched for markdown compiler and found these two:
- https://www.npmjs.com/package/markdown-it
- https://www.npmjs.com/package/showdown

I will try to use markdown-it, because there are some plugins for itand if we need we could write one on our own.

**Comment by aeimer** [comment]
Works, will close this Issue.
