### ISSUE TITLE
Enhance video upload to be able to cope with all types of files (... and display them in the frontend)

### ISSUE THREAD

**Issue by d89** [h-da/geli#97]
# User Story

### As a: 

Teacher

### I want:

... to be able to upload every kind of file (most importantly pdf, ppt(x), doc(x), jp(e)g, png, zip, xls(x), mp4, mov, flv, h264)

### so that:

I can provide the students with downloadable files in the course frontend.

## Acceptance criteria:

- [ ] file icons for common mimetypes (as listed above)
- [x] images are displayed in a small version (no thumbnail generation required)
- [x] videos are displayed in a video player

**Comment by felixbrucker** [comment]
At first we should only support native media formats for live video playback (https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats), serverside conversion of proprietary formats like apple MOV container for quicktime or FLV container for flash videos could be done at a later stage IMHO.
We could however offer to just download unsupported formats as regular files, without "in browser" playback.
